SoftProcessorUnit/Syntax/BTC.h File Reference
#include `BTCDefs.h`
Functions
OPBACKTRANSLATE_FUNC (clear, { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(add
OPBACKTRANSLATE_FUNC (cos, { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(sqrt
OPBACKTRANSLATE_FUNC (dec, { OPBACKGENERAL({ ADDSPI(1);ComplexValue val={};ComplexValueResult valResult=retrieveComplexValue(SPI, &val);if(valResult==SPU_CV_NOARG) return SPU_DISASM_OK;COMPLEXVALOK;renderComplexValue(&val, params->outputFile);}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(call
OPBACKTRANSLATE_FUNC (div, { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(sin
OPBACKTRANSLATE_FUNC (in, { OPBACKGENERAL({ ADDSPI(1);ComplexValue val={};ComplexValueResult valResult=retrieveComplexValue(SPI, &val);if(valResult==SPU_CV_NOARG) return SPU_DISASM_OK;COMPLEXVALOK;renderComplexValue(&val, params->outputFile);}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(dump
OPBACKTRANSLATE_FUNC (ja, { OPBACKGENERAL({ char *localSPI= *SPI;int *val=(int *)(localSPI+1);fprintf(params->outputFile, `%d`, *val);ADDSPI(5);}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(jae
OPBACKTRANSLATE_FUNC (jb, { OPBACKGENERAL({ char *localSPI= *SPI;int *val=(int *)(localSPI+1);fprintf(params->outputFile, `%d`, *val);ADDSPI(5);}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(jbe
OPBACKTRANSLATE_FUNC (je, { OPBACKGENERAL({ char *localSPI= *SPI;int *val=(int *)(localSPI+1);fprintf(params->outputFile, `%d`, *val);ADDSPI(5);}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(jne
OPBACKTRANSLATE_FUNC (jm, { OPBACKGENERAL({ char *localSPI= *SPI;int *val=(int *)(localSPI+1);fprintf(params->outputFile, `%d`, *val);ADDSPI(5);}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(inc
OPBACKTRANSLATE_FUNC (out, { OPBACKGENERAL({ ADDSPI(1);ComplexValue val={};ComplexValueResult valResult=retrieveComplexValue(SPI, &val);if(valResult==SPU_CV_NOARG) return SPU_DISASM_OK;COMPLEXVALOK;renderComplexValue(&val, params->outputFile);}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(jmp
OPBACKTRANSLATE_FUNC (pow, { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(hlt
OPBACKTRANSLATE_FUNC (push, { OPBACKGENERAL({ if(!checkBytesEnoughNumber(binary, *SPI, 10)){ return SPU_DISASM_NOTENOUGHARGS;} ADDSPI(1);ComplexValue val={};ComplexValueResult valResult=retrieveComplexValue(SPI, &val);COMPLEXVALOK;renderComplexValue(&val, params->outputFile);}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(pop
OPBACKTRANSLATE_FUNC (ret, { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(mov
OPBACKTRANSLATE_FUNC (sub, { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;}) OPBACKTRANSLATE_FUNC(mul
Function Documentation
OPBACKTRANSLATE_FUNC() [1/14]
OPBACKTRANSLATE_FUNC (clear , { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;})
References INCSPI, OPBACKGENERAL, and SPU_DISASM_OK.
OPBACKTRANSLATE_FUNC() [2/14]
OPBACKTRANSLATE_FUNC (cos , { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;})
References INCSPI, OPBACKGENERAL, and SPU_DISASM_OK.
OPBACKTRANSLATE_FUNC() [3/14]
OPBACKTRANSLATE_FUNC (dec , [{ OPBACKGENERAL({ ADDSPI(1);ComplexValue val={};ComplexValueResult valResult=retrieveComplexValue(SPI, &val);if(valResult==SPU_CV_NOARG) return SPU_DISASM_OK;COMPLEXVALOK;renderComplexValue(&val, params->outputFile);}) return SPU_DISASM_OK;}])
References ADDSPI, COMPLEXVALOK, OPBACKGENERAL, renderComplexValue(), retrieveComplexValue(), SPU_CV_NOARG, SPU_DISASM_OK, and val.
OPBACKTRANSLATE_FUNC() [4/14]
OPBACKTRANSLATE_FUNC (div , { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;})
References INCSPI, OPBACKGENERAL, and SPU_DISASM_OK.
OPBACKTRANSLATE_FUNC() [5/14]
OPBACKTRANSLATE_FUNC (in , [{ OPBACKGENERAL({ ADDSPI(1);ComplexValue val={};ComplexValueResult valResult=retrieveComplexValue(SPI, &val);if(valResult==SPU_CV_NOARG) return SPU_DISASM_OK;COMPLEXVALOK;renderComplexValue(&val, params->outputFile);}) return SPU_DISASM_OK;}])
References ADDSPI, COMPLEXVALOK, OPBACKGENERAL, renderComplexValue(), retrieveComplexValue(), SPU_CV_NOARG, SPU_DISASM_OK, and val.
OPBACKTRANSLATE_FUNC() [6/14]
OPBACKTRANSLATE_FUNC (ja , [{ OPBACKGENERAL({ char *localSPI= *SPI;int *val=(int *)(localSPI+1);fprintf(params->outputFile, `%d`, *val);ADDSPI(5);}) return SPU_DISASM_OK;}])
References ADDSPI, localSPI, OPBACKGENERAL, SPU_DISASM_OK, and val.
OPBACKTRANSLATE_FUNC() [7/14]
OPBACKTRANSLATE_FUNC (jb , [{ OPBACKGENERAL({ char *localSPI= *SPI;int *val=(int *)(localSPI+1);fprintf(params->outputFile, `%d`, *val);ADDSPI(5);}) return SPU_DISASM_OK;}])
References ADDSPI, localSPI, OPBACKGENERAL, SPU_DISASM_OK, and val.
OPBACKTRANSLATE_FUNC() [8/14]
OPBACKTRANSLATE_FUNC (je , [{ OPBACKGENERAL({ char *localSPI= *SPI;int *val=(int *)(localSPI+1);fprintf(params->outputFile, `%d`, *val);ADDSPI(5);}) return SPU_DISASM_OK;}])
References ADDSPI, localSPI, OPBACKGENERAL, SPU_DISASM_OK, and val.
OPBACKTRANSLATE_FUNC() [9/14]
OPBACKTRANSLATE_FUNC (jm , [{ OPBACKGENERAL({ char *localSPI= *SPI;int *val=(int *)(localSPI+1);fprintf(params->outputFile, `%d`, *val);ADDSPI(5);}) return SPU_DISASM_OK;}])
References ADDSPI, localSPI, OPBACKGENERAL, SPU_DISASM_OK, and val.
OPBACKTRANSLATE_FUNC() [10/14]
OPBACKTRANSLATE_FUNC (out , [{ OPBACKGENERAL({ ADDSPI(1);ComplexValue val={};ComplexValueResult valResult=retrieveComplexValue(SPI, &val);if(valResult==SPU_CV_NOARG) return SPU_DISASM_OK;COMPLEXVALOK;renderComplexValue(&val, params->outputFile);}) return SPU_DISASM_OK;}])
References ADDSPI, COMPLEXVALOK, OPBACKGENERAL, renderComplexValue(), retrieveComplexValue(), SPU_CV_NOARG, SPU_DISASM_OK, and val.
OPBACKTRANSLATE_FUNC() [11/14]
OPBACKTRANSLATE_FUNC (pow , { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;})
References INCSPI, OPBACKGENERAL, and SPU_DISASM_OK.
OPBACKTRANSLATE_FUNC() [12/14]
OPBACKTRANSLATE_FUNC (push , [{ OPBACKGENERAL({ if(!checkBytesEnoughNumber(binary, *SPI, 10)){ return SPU_DISASM_NOTENOUGHARGS;} ADDSPI(1);ComplexValue val={};ComplexValueResult valResult=retrieveComplexValue(SPI, &val);COMPLEXVALOK;renderComplexValue(&val, params->outputFile);}) return SPU_DISASM_OK;}])
References ADDSPI, checkBytesEnoughNumber(), COMPLEXVALOK, OPBACKGENERAL, renderComplexValue(), retrieveComplexValue(), SPU_DISASM_NOTENOUGHARGS, SPU_DISASM_OK, and val.
OPBACKTRANSLATE_FUNC() [13/14]
OPBACKTRANSLATE_FUNC (ret , { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;})
References INCSPI, OPBACKGENERAL, and SPU_DISASM_OK.
OPBACKTRANSLATE_FUNC() [14/14]
OPBACKTRANSLATE_FUNC (sub , { OPBACKGENERAL({ INCSPI;}) return SPU_DISASM_OK;})
References INCSPI, OPBACKGENERAL, and SPU_DISASM_OK.