SoftProcessorUnit/Syntax/Translation/MacroSyntax/BTCDefs.h File Reference
#include `ParseHelpers.hpp`
Macros
#define ADDSPI(n) (*SPI) += n
#define COMPLEXVALOK
#define INCSPI (*SPI)++
#define MOVSPI(n) (*SPI) = n
#define OPBACKGENERAL(code)
Functions
int checkBytesEnough (const SyntaxEntity *thou, BinaryFile *binary, char *SPI)
int checkBytesEnoughNumber (BinaryFile *binary, const char *SPI, size_t bytes)
Macro Definition Documentation
ADDSPI
#define ADDSPI(n) (*SPI) += n
COMPLEXVALOK
#define COMPLEXVALOK
Value:
switch(valResult) { \
case SPU_CV_WRONGSTRUCT: \
return SPU_DISASM_WRONG_CMDFORMAT;\
case SPU_CV_WRONGREG: \
return SPU_DISASM_WRONG_CMDFORMAT; \
case SPU_CV_WRONGNUM: \
return SPU_DISASM_WRONG_CMDFORMAT; \
case SPU_CV_WRONGOP: \
return SPU_DISASM_WRONG_CMDFORMAT; \
case SPU_CV_NOARG:\
return SPU_DISASM_WRONG_CMDFORMAT; \
case SPU_CV_OK: \
break;\
} \
INCSPI
STACKRESULT INCSPI (*SPI)++
MOVSPI
#define MOVSPI(n) (*SPI) = n
OPBACKGENERAL
#define OPBACKGENERAL(code)
Value:
{ \
fprintf(params->outputFile, "%s ", thou->naming);\
if (checkBytesEnough(thou, binary, *SPI) == 0) {return SPU_DISASM_NOTENOUGHARGS;}\
code \
fprintf(params->outputFile, "\n"); }
Function Documentation
checkBytesEnough()
int checkBytesEnough (const SyntaxEntity * thou, BinaryFile * binary, char * SPI)
                                                                              {
    size_t neededBytes = 1;
    
    neededBytes += (size_t)(thou->flagBytes);
    for (size_t i = 0; i < strlen(thou->format); i++) {
        if (thou->format[i] == '*')
            neededBytes++;
    }
    
    return checkBytesEnoughNumber(binary, SPI, neededBytes);
}
References checkBytesEnoughNumber(), SyntaxEntity::flagBytes, SyntaxEntity::format, and i.
checkBytesEnoughNumber()
int checkBytesEnoughNumber (BinaryFile * binary, const char * SPI, size_t bytes)
                                                                              {
    if (SPI + bytes > binary->code + binary->currentSize)
        return 0;
    return 1;
}
References BinaryFile::code, and BinaryFile::currentSize.
Referenced by checkBytesEnough(), and OPBACKTRANSLATE_FUNC().