SoftProcessorUnit/Assembly/Helpers/AnalysisAndPreparing/CodeAnalysis.hpp File Reference
#include <cstdio>
#include `Syntax.hpp`
#include `AssemblyDTypes.hpp`
#include `AssemblyHelpers.hpp`
#include `CommandsParser.hpp`
#include `StringDistance.hpp`
Functions
int analyzeInstructionErrors (SyntaxMapping *mapping, AssemblyParams *params, BinaryFile *binary, char *line, int lineNo)
int analyzeInstructionWarnings (SyntaxMapping *mapping, AssemblyParams *params, char *line)
void analyzeLabelsErrors (AssemblyParams *params)
const SyntaxEntity * bestMatchCommand (SyntaxMapping *mapping, char *command)
int findLineWithSubstrung (char *code, char *substr)
int generateErrors (SyntaxMapping *mapping, AssemblyParams *params, char *code)
Function Documentation
analyzeInstructionErrors()
int analyzeInstructionErrors (SyntaxMapping * mapping, AssemblyParams * params, BinaryFile * binary, char * line, int lineNo)
                                                                                                                         {
    size_t len = strlen(line);
    char* trimmed = (char*)calloc(len + 1, 1);
    len = trimwhitespace(trimmed, len + 1, line);
    
    
    if (trimmed[0] == ';' || len <= 1){
        free(trimmed);
        return 1;
    }
    
    int argc = 0;
    const SyntaxEntity* foundEntity = fetchCommand(mapping, trimmed);
    int argsLen[SPU_CMD_MAXARGS] = {0};
    const char** argv = getArgList(trimmed, &argc, argsLen);
    
    if (foundEntity == nullptr) {
        LabelParse resLabel = parseLabel(params, line);
        if (resLabel == SPU_LABEL_NOTFOUND) {
            const SyntaxEntity* best = bestMatchCommand(mapping, trimmed);
            fprintf(stderr, "%s:%d:1: error: unknown instruction found; maybe you ment '%s'?\n%s\n",params->inputFileRealName, lineNo, best->naming, trimmed);
            fprintf(stderr, "^");
            for (size_t i = 1; i < len; i++) {
                if (trimmed[i] == ' ') {
                    fprintf(stderr, "\n");
                    break;
                }
                fprintf(stderr, "~");
            }
            
            fprintf(stderr, "%s\n", best->naming);
            
            free(trimmed);
            freeArgList((char**)argv, argc);
            return 0;
        } else {
            setLabelPos(params, trimmed, (unsigned int) binary->currentSize);
            freeArgList((char**)argv, argc);
            free(trimmed);
            return 1;
        }
    }
    
    int validArguments = isValidArgumentsNumber(foundEntity, argc - 1);
    
    if (validArguments != 1) {
        fprintf(stderr, "%s:%d:1: error: invalid arguments; expected: '%s'\n%s\n", params->inputFileRealName, lineNo, foundEntity->format, trimmed);
        for (int i = 0; i < argsLen[0]; i++) {
            fprintf(stderr, " ");
        }
        fprintf(stderr, " ^");
        for (int i = 1; i < SPU_CMD_MAXARGS; i++) {
            for (int j = 0; j < argsLen[i]; j++) {
                fprintf(stderr, "~");
            }
        }
        fprintf(stderr, "\n");
        free(trimmed);
        freeArgList((char**)argv, argc);
        return 0;
    }
    
    CommandToBytesResult parseRes = foundEntity->cProcessor(foundEntity, params, binary, argc, argv);
    
    switch (parseRes) {
        case SPU_CTB_ERROR:{
            fprintf(stderr, "%s:%d:1: error: assembly: general syntax error\n", params->inputFileRealName, lineNo);
            break;
        }
        case SPU_CTB_UNKNOWN_REGISTER:{
            fprintf(stderr, "%s:%d:1: error: assembly: unknown register\n", params->inputFileRealName, lineNo);
            break;
        }
        case SPU_CTB_INVALID_NUMBER:{
            fprintf(stderr, "%s:%d:1: error: assembly: invalid number of arguments\n", params->inputFileRealName, lineNo);
            break;
        }
        case SPU_CTB_INVALID_ARGSTRUCTURE: {
            fprintf(stderr, "%s:%d:1: error: assembly: invalid argument structure\n", params->inputFileRealName, lineNo);
            break;
        }
        case SPU_CTB_OK:{
            break;
        }
        case SPU_CTB_NONASSIGNABLE: {
            fprintf(stderr, "%s:%d:1: error: assembly: argument is nonassignable\n", params->inputFileRealName, lineNo);
            break;
        }
    }
    
    free(trimmed);
    freeArgList((char**)argv, argc);
    return 1;
}
References bestMatchCommand(), SyntaxEntity::cProcessor, BinaryFile::currentSize, fetchCommand(), SyntaxEntity::format, freeArgList(), getArgList(), i, AssemblyParams::inputFileRealName, isValidArgumentsNumber(), SyntaxEntity::naming, parseLabel(), setLabelPos(), SPU_CMD_MAXARGS, SPU_CTB_ERROR, SPU_CTB_INVALID_ARGSTRUCTURE, SPU_CTB_INVALID_NUMBER, SPU_CTB_NONASSIGNABLE, SPU_CTB_OK, SPU_CTB_UNKNOWN_REGISTER, SPU_LABEL_NOTFOUND, and trimwhitespace().
Referenced by generateErrors().
analyzeInstructionWarnings()
int analyzeInstructionWarnings (SyntaxMapping * mapping, AssemblyParams * params, char * line)
analyzeLabelsErrors()
void analyzeLabelsErrors (AssemblyParams * params)
                                                {
    JMPLabel* current = params->labelsStore->first;
    
    while(current != nullptr) {
        if (current->name == nullptr)
            break;
        if (current->positionTo == -1) {
            int lineNo = findLineWithSubstrung(params->codeText, current->name);
            printf("%s:%d:1: error: assembly: no label specified for '%s' jump\n", params->inputFileRealName, lineNo, current->name);
        }
        
        if (current->positionFrom == -1) {
            int lineNo = findLineWithSubstrung(params->codeText, current->name);
            printf("%s:%d:1: warning: assembly: label '%s' has no jump instructions\n", params->inputFileRealName,lineNo, current->name);
        }
        
        if (current->used > 1) {
            int lineNo = findLineWithSubstrung(params->codeText, current->name);
            printf("%s:%d:1: error: assembly: label '%s' has several definitions\n", params->inputFileRealName,lineNo, current->name);
        }
        
        current = current->next;
    }
}
References AssemblyParams::codeText, findLineWithSubstrung(), JMPLabelsStore::first, AssemblyParams::inputFileRealName, AssemblyParams::labelsStore, JMPLabel::name, JMPLabel::next, JMPLabel::positionFrom, JMPLabel::positionTo, printf(), and JMPLabel::used.
Referenced by generateErrors().
bestMatchCommand()
const SyntaxEntity* bestMatchCommand (SyntaxMapping * mapping, char * command)
                                                                            {
    char* nextInstr = strchr(command, ' ');
    if (nextInstr != nullptr){
        *nextInstr = '\0';
    }
    
    int minValue = 0;
    int index = -1;
    for (size_t i = 0; i < mapping->number; i++) {
        LevenshteinEdit *script;
        size_t distance = levenshtein_distance(mapping->entities[i].naming, command, &script);
        if (index == -1 || minValue > (int)distance){
            minValue = (int)distance;
            index = (int)i;
        }
    }
    if (nextInstr != nullptr){
        *nextInstr = ' ';
    }
    
    return mapping->entities + index;
}
References SyntaxMapping::entities, i, int, levenshtein_distance(), SyntaxEntity::naming, and SyntaxMapping::number.
Referenced by analyzeInstructionErrors().
findLineWithSubstrung()
int findLineWithSubstrung (char * code, char * substr)
                                                   {
    char* newInstruction = code;
    int lineNo = 0;
    if (substr == nullptr || code == nullptr)
        return -1;
    
    while (newInstruction > (char*)(1)) {
        char* newlinePos = strchr(newInstruction, '\n');
        if (newlinePos != nullptr){
            *newlinePos = '\0';
        }
        
        char* commPos = strchr(newInstruction, ';');
        if (commPos == newInstruction) {
            if (newlinePos != nullptr){
                *newlinePos = '\n';
            }
            newInstruction = strchr(newInstruction + 1, '\n');
            continue;
        }
        if (commPos != nullptr){
            *commPos = '\0';
        }
        ++lineNo;
        if(strstr(newInstruction, substr) != nullptr) {
            return lineNo;
        }
       
        if (commPos != nullptr){
            *commPos = ';';
        }
        
        if (newlinePos != nullptr){
            *newlinePos = '\n';
        }
        newInstruction = strchr(newInstruction, '\n') + 1;
    }
    
    return -1;
}
Referenced by analyzeLabelsErrors().
generateErrors()
int generateErrors (SyntaxMapping * mapping, AssemblyParams * params, char * code)
                                                                               {
    char* newInstruction = code;
    int result = 1;
    int lineNo = 0;
    
    size_t length = strlen(code);
    removeWhitespacesInTheEnd(code, &length);
    removeWhitespacesInTheBeginning(code, &length);
    
    AssemblyParams localParams = {};
    localParams.labelsStore = new JMPLabelsStore();
    localParams.verbose = 0;
    localParams.codeText = code;
    localParams.inputFileName = params->inputFileName;
    localParams.inputFileRealName = params->inputFileRealName;
    localParams.outputFileName = params->outputFileName;
    
    BinaryFile* binary = NewBinaryFile();
    
    while (newInstruction > (char*)(1)) {
        char* newlinePos = strchr(newInstruction, '\n');
        if (newlinePos != nullptr){
            *newlinePos = '\0';
        }
        
        char* commPos = strchr(newInstruction, ';');
        if (commPos == newInstruction) {
            if (newlinePos != nullptr){
                *newlinePos = '\n';
            }
            newInstruction = strchr(newInstruction + 1, '\n');
            continue;
        }
        if (commPos != nullptr){
            *commPos = '\0';
        }
        
        result &= analyzeInstructionErrors(mapping, &localParams, binary, newInstruction, ++lineNo);
        
        if (commPos != nullptr){
            *commPos = ';';
        }
        
        if (newlinePos != nullptr){
            *newlinePos = '\n';
        }
        newInstruction = strchr(newInstruction, '\n') + 1;
    }
    DestructBinaryFile(binary);
    LabelParse completeTable = labelsTableComplete(&localParams, 1);
    analyzeLabelsErrors(&localParams);
    if (completeTable != SPU_LABEL_OK) {
        labelsTableComplete(&localParams, 0);
        delete localParams.labelsStore;
        return 0;
    }
    
    delete params->labelsStore;
    params->labelsStore = localParams.labelsStore;
    return result;
}
References analyzeInstructionErrors(), analyzeLabelsErrors(), AssemblyParams::codeText, DestructBinaryFile(), AssemblyParams::inputFileName, AssemblyParams::inputFileRealName, AssemblyParams::labelsStore, labelsTableComplete(), NewBinaryFile(), AssemblyParams::outputFileName, removeWhitespacesInTheBeginning(), removeWhitespacesInTheEnd(), result, SPU_LABEL_OK, and AssemblyParams::verbose.
Referenced by main().