SoftProcessorUnit/SPU/Core/VIdeo/CoreRender.cpp File Reference
#include `CoreRender.hpp`
#include <stdio.h>
#include <stdlib.h>
Functions
void fillBlank (SPUCore *core)
void renderVRAM (SPUCore *core)
int vramSetPixel (SPUCore *core, int x, int y, char val)
Function Documentation
fillBlank()
void fillBlank (SPUCore * core)
                             {
    for(int h = 0; h < SCREEN_HEIGHT; h++){
        for(int w = 0; w < SCREEN_WIDTH; w++){
            *(((char*)core->RAM) + VRAM_OFFSET * sizeof(double) + (SCREEN_WIDTH * h) + w) = ' ';
        }
    }
}
References SPUCore::RAM, SCREEN_HEIGHT, SCREEN_WIDTH, and VRAM_OFFSET.
Referenced by ConstructSPUCore().
renderVRAM()
void renderVRAM (SPUCore * core)
                              {
// printf("\x1b[2J");
    printf("\x1b[H");
    for(int h = 0; h < SCREEN_HEIGHT; h++){
        for(int w = 0; w < SCREEN_WIDTH; w++){
            putchar(*(((char*)core->RAM)
                      + VRAM_OFFSET * sizeof(double)
                      + (SCREEN_WIDTH * h)
                      + w));
        }
        putchar(10);
    }
}
References printf(), SPUCore::RAM, SCREEN_HEIGHT, SCREEN_WIDTH, and VRAM_OFFSET.
Referenced by OPEXE_FUNC(), and runCode().
vramSetPixel()
int vramSetPixel (SPUCore * core, int x, int y, char val)
                                                        {
    char* start = ((char*)core->RAM) + VRAM_OFFSET * sizeof(double);
    start += y * SCREEN_WIDTH;
    start += x;
    *start = val;
    return 1;
}
References SPUCore::RAM, SCREEN_WIDTH, val, VRAM_OFFSET, x, and y.