SoftProcessorUnit/Syntax/CTB.h File Reference
#include `CTBDefs.h`
Functions
OPTRANSLATE_FUNC (abs, { JUSTCOMMAND })
OPTRANSLATE_FUNC (add, { JUSTCOMMAND })
OPTRANSLATE_FUNC (call, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (clear, { JUSTCOMMAND })
OPTRANSLATE_FUNC (clrscr, { JUSTCOMMAND })
OPTRANSLATE_FUNC (cos, { JUSTCOMMAND })
OPTRANSLATE_FUNC (dec, { ZEROORSTORAGE;})
OPTRANSLATE_FUNC (div, { JUSTCOMMAND })
OPTRANSLATE_FUNC (dump, { JUSTCOMMAND })
OPTRANSLATE_FUNC (hlt, { JUSTCOMMAND })
OPTRANSLATE_FUNC (in, { ZEROORSTORAGE;})
OPTRANSLATE_FUNC (inc, { ZEROORSTORAGE;})
OPTRANSLATE_FUNC (ja, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (jae, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (jb, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (jbe, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (je, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (jm, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (jmp, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (jne, { LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (mov, { LSTDUMPED({ APPENDCHAR(thou->code);ComplexValue val=GETCOMPLEXVALNO(1);COMPLEXVALOK int assignable=complexValueAssignable(&val);if(assignable !=1) return SPU_CTB_NONASSIGNABLE;writeComplexArg(&val, binary);val=GETCOMPLEXVALNO(2);COMPLEXVALOK;writeComplexArg(&val, binary);}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (mul, { JUSTCOMMAND })
OPTRANSLATE_FUNC (out, { ZEROORVAL;})
OPTRANSLATE_FUNC (pixset, { LSTDUMPED({ APPENDCHAR(thou->code);ComplexValue val=GETCOMPLEXVALNO(1);COMPLEXVALOK writeComplexArg(&val, binary);val=GETCOMPLEXVALNO(2);COMPLEXVALOK;writeComplexArg(&val, binary);val=GETCOMPLEXVALNO(3);COMPLEXVALOK;writeComplexArg(&val, binary);}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (pop, { ZEROORSTORAGE;})
OPTRANSLATE_FUNC (pow, { JUSTCOMMAND })
OPTRANSLATE_FUNC (push, { LSTDUMPED({ APPENDCHAR(thou->code);ComplexValue val=GETCOMPLEXVALNO(1);COMPLEXVALOK writeComplexArg(&val, binary);}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (rend, { JUSTCOMMAND;})
OPTRANSLATE_FUNC (ret, { JUSTCOMMAND;})
OPTRANSLATE_FUNC (sin, { JUSTCOMMAND })
OPTRANSLATE_FUNC (slp, { LSTDUMPED({ APPENDCHAR(thou->code);ComplexValue val=GETCOMPLEXVALNO(1);COMPLEXVALOK writeComplexArg(&val, binary);}) return SPU_CTB_OK;})
OPTRANSLATE_FUNC (sqrt, { JUSTCOMMAND })
OPTRANSLATE_FUNC (sub, { JUSTCOMMAND })
Function Documentation
OPTRANSLATE_FUNC() [1/33]
OPTRANSLATE_FUNC (abs , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [2/33]
OPTRANSLATE_FUNC (add , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [3/33]
OPTRANSLATE_FUNC (call , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [4/33]
OPTRANSLATE_FUNC (clear , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [5/33]
OPTRANSLATE_FUNC (clrscr , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [6/33]
OPTRANSLATE_FUNC (cos , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [7/33]
OPTRANSLATE_FUNC (dec , { ZEROORSTORAGE;})
References ZEROORSTORAGE.
OPTRANSLATE_FUNC() [8/33]
OPTRANSLATE_FUNC (div , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [9/33]
OPTRANSLATE_FUNC (dump , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [10/33]
OPTRANSLATE_FUNC (hlt , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [11/33]
OPTRANSLATE_FUNC (in , { ZEROORSTORAGE;})
References ZEROORSTORAGE.
OPTRANSLATE_FUNC() [12/33]
OPTRANSLATE_FUNC (inc , { ZEROORSTORAGE;})
References ZEROORSTORAGE.
OPTRANSLATE_FUNC() [13/33]
OPTRANSLATE_FUNC (ja , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [14/33]
OPTRANSLATE_FUNC (jae , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [15/33]
OPTRANSLATE_FUNC (jb , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [16/33]
OPTRANSLATE_FUNC (jbe , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [17/33]
OPTRANSLATE_FUNC (je , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [18/33]
OPTRANSLATE_FUNC (jm , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [19/33]
OPTRANSLATE_FUNC (jmp , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [20/33]
OPTRANSLATE_FUNC (jne , [{ LSTDUMPED({ APPENDCHAR(thou->code);SETLABELPOS;int jumpOffset=(int)(GETLABELPOS);APPENDDATA(&jumpOffset, sizeof(jumpOffset));}) return SPU_CTB_OK;}])
References APPENDCHAR, APPENDDATA, GETLABELPOS, int, LSTDUMPED, SETLABELPOS, and SPU_CTB_OK.
OPTRANSLATE_FUNC() [21/33]
OPTRANSLATE_FUNC (mov , [{ LSTDUMPED({ APPENDCHAR(thou->code);ComplexValue val=GETCOMPLEXVALNO(1);COMPLEXVALOK int assignable=complexValueAssignable(&val);if(assignable !=1) return SPU_CTB_NONASSIGNABLE;writeComplexArg(&val, binary);val=GETCOMPLEXVALNO(2);COMPLEXVALOK;writeComplexArg(&val, binary);}) return SPU_CTB_OK;}])
References APPENDCHAR, COMPLEXVALOK, complexValueAssignable(), GETCOMPLEXVALNO, LSTDUMPED, SPU_CTB_NONASSIGNABLE, SPU_CTB_OK, val, and writeComplexArg().
OPTRANSLATE_FUNC() [22/33]
OPTRANSLATE_FUNC (mul , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [23/33]
OPTRANSLATE_FUNC (out , { ZEROORVAL;})
References ZEROORVAL.
OPTRANSLATE_FUNC() [24/33]
OPTRANSLATE_FUNC (pixset , [{ LSTDUMPED({ APPENDCHAR(thou->code);ComplexValue val=GETCOMPLEXVALNO(1);COMPLEXVALOK writeComplexArg(&val, binary);val=GETCOMPLEXVALNO(2);COMPLEXVALOK;writeComplexArg(&val, binary);val=GETCOMPLEXVALNO(3);COMPLEXVALOK;writeComplexArg(&val, binary);}) return SPU_CTB_OK;}])
References APPENDCHAR, COMPLEXVALOK, GETCOMPLEXVALNO, LSTDUMPED, SPU_CTB_OK, val, and writeComplexArg().
OPTRANSLATE_FUNC() [25/33]
OPTRANSLATE_FUNC (pop , { ZEROORSTORAGE;})
References ZEROORSTORAGE.
OPTRANSLATE_FUNC() [26/33]
OPTRANSLATE_FUNC (pow , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [27/33]
OPTRANSLATE_FUNC (push , [{ LSTDUMPED({ APPENDCHAR(thou->code);ComplexValue val=GETCOMPLEXVALNO(1);COMPLEXVALOK writeComplexArg(&val, binary);}) return SPU_CTB_OK;}])
References APPENDCHAR, COMPLEXVALOK, GETCOMPLEXVALNO, LSTDUMPED, SPU_CTB_OK, val, and writeComplexArg().
OPTRANSLATE_FUNC() [28/33]
OPTRANSLATE_FUNC (rend , { JUSTCOMMAND;})
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [29/33]
OPTRANSLATE_FUNC (ret , { JUSTCOMMAND;})
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [30/33]
OPTRANSLATE_FUNC (sin , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [31/33]
OPTRANSLATE_FUNC (slp , [{ LSTDUMPED({ APPENDCHAR(thou->code);ComplexValue val=GETCOMPLEXVALNO(1);COMPLEXVALOK writeComplexArg(&val, binary);}) return SPU_CTB_OK;}])
References APPENDCHAR, COMPLEXVALOK, GETCOMPLEXVALNO, LSTDUMPED, SPU_CTB_OK, val, and writeComplexArg().
OPTRANSLATE_FUNC() [32/33]
OPTRANSLATE_FUNC (sqrt , { JUSTCOMMAND })
References JUSTCOMMAND.
OPTRANSLATE_FUNC() [33/33]
OPTRANSLATE_FUNC (sub , { JUSTCOMMAND })
References JUSTCOMMAND.