SoftProcessorUnit/Disassembly/Helpers/DisAssemblyHelpers.cpp File Reference
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include `DisAssemblyHelpers.hpp`
#include `AssemblyHelpers.hpp`
#include `CommandsParser.hpp`
#include `SPUVersion.hpp`
#include `Syntax.hpp`
Functions
void DestructDisAssemblyParams (DisassemblyParams *params)
DisassemblyParseResult disAssamblyCode (DisassemblyParams *params, struct SyntaxMapping *mapping, BinaryFile *binary)
DisassemblyParseResult disAssamblyInstruction (DisassemblyParams *params, struct SyntaxMapping *mapping, BinaryFile *binary, char **instruction)
int parseArgs (int argc, const char *argv[], DisassemblyParams *params)
void printDisAssemblyHelpData ()
Function Documentation
DestructDisAssemblyParams()
void DestructDisAssemblyParams (DisassemblyParams * params)
                                                          {
    fclose(params->inputFile);
    fclose(params->outputFile);
    delete params->labels;
}
References DisassemblyParams::inputFile, DisassemblyParams::labels, and DisassemblyParams::outputFile.
Referenced by main().
disAssamblyCode()
DisassemblyParseResult disAssamblyCode (DisassemblyParams * params, struct SyntaxMapping * mapping, BinaryFile * binary)
                                                           {
    char* SPI = binary->code;
    
    while(SPI < binary->code + binary->currentSize) {
        DisassemblyParseResult cmdRes = disAssamblyInstruction(params, mapping, binary, &SPI);
        if (cmdRes != SPU_DISASM_OK) {
            return cmdRes;
        }
    }
    
    return SPU_DISASM_OK;
}
References BinaryFile::code, BinaryFile::currentSize, disAssamblyInstruction(), and SPU_DISASM_OK.
Referenced by main().
disAssamblyInstruction()
DisassemblyParseResult disAssamblyInstruction (DisassemblyParams * params, struct SyntaxMapping * mapping, BinaryFile * binary, char ** instruction)
                                                                  {
    char instructionId = **instruction;
    
    const SyntaxEntity* entity = getSyntaxEntityByCode(mapping, instructionId);
    
    if (entity == nullptr) {
        printf("error: disassembly: found unknown command (%d) or invalid sequence formation\n", instructionId);
        return SPU_DISASM_UNKNOWN_CMD;
    }
    
    if (params->verbose){
        printf("info: disassembly: processing %s command...\n", entity->naming);
    }
    
    DisassemblyParseResult parseRes = entity->bProcessor(entity, params, binary, instruction);
    
    if (parseRes != SPU_DISASM_OK){
        printf("error: disassembly: error while processing %s\n", entity->naming);
        return parseRes;
    }
        
    return SPU_DISASM_OK;
}
References SyntaxEntity::bProcessor, getSyntaxEntityByCode(), SyntaxEntity::naming, printf(), SPU_DISASM_OK, SPU_DISASM_UNKNOWN_CMD, and DisassemblyParams::verbose.
Referenced by disAssamblyCode().
parseArgs()
int parseArgs (int argc, const char * argv[], DisassemblyParams * params)
                                                                       {
    DisassemblyParams newParams = {nullptr, nullptr, nullptr, nullptr, nullptr, 0};
    newParams.labels = new JMPLabelsStore();
    
    if (argc <= 1){
        printDisAssemblyHelpData();
    }
    for(int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--input") == 0) {
            if (i + 1 > argc){
                printf("error: disassembly: No input file specified after --input\n");
                return EXIT_FAILURE;
            }
            FILE* inputFile = fopen(argv[i + 1], "rb");
            newParams.inputFile = inputFile;
            newParams.inputFileName = *(argv + i + 1);
            if (newParams.inputFile == nullptr){
                printf("error: disassembly: Can't open input file\n");
                return EXIT_FAILURE;
            }
            i++;
        }else if (strcmp(argv[i], "--output") == 0) {
            if (i + 1 > argc){
                printf("error: disassembly: No output file specified after --output\n");
                return EXIT_FAILURE;
            }
            FILE* outputFile = fopen(argv[i + 1], "wb");
            newParams.outputFile = outputFile;
            newParams.outputFileName = *(argv + i + 1);
            i++;
        }else if (strcmp(argv[i], "--verbose") == 0) {
            newParams.verbose = 1;
        }else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            printDisAssemblyHelpData();
        }else {
            if (newParams.inputFile == nullptr){
                FILE* inputFile = fopen(argv[i], "rb");
                newParams.inputFile = inputFile;
                newParams.inputFileName = *(argv + i);
                if (newParams.inputFile == nullptr){
                    printf("error: disassembly: Can't open input file %s\n", argv[i]);
                    return EXIT_FAILURE;
                }
            }
        }
    }
    
    if (newParams.inputFile == nullptr) {
        printf("error: disassembly: No input file specified\n");
        return EXIT_FAILURE;
    }
    
    if (newParams.outputFile == nullptr) {
        newParams.outputFile = stdout;
        newParams.outputFileName = "stdout";
        if (newParams.outputFile == nullptr){
            printf("error: disassembly: No output file specified\n");
            return EXIT_FAILURE;
        }
    }
    
    *params = newParams;
    
    return EXIT_SUCCESS;
}
References i, DisassemblyParams::inputFile, DisassemblyParams::inputFileName, DisassemblyParams::labels, DisassemblyParams::outputFile, DisassemblyParams::outputFileName, printDisAssemblyHelpData(), printf(), and DisassemblyParams::verbose.
printDisAssemblyHelpData()
void printDisAssemblyHelpData ()
                                {
    int SPUAssemblyVersion = SPU_VERSION;
    char* SPUAssemblyVersion_chars = (char*)&SPUAssemblyVersion;
    printf("SPUDisAssembly v%c.%c.%c%c help\n"
           "--input <input file> input file to be assembled .spub format (spu binary)\n"
           "--output <output file> output file. stdout by default (spu source)\n"
           "-h, --help show this help message\n"
           "--verbose output disassembly debug information to the console\n"
           "\n",
           SPUAssemblyVersion_chars[0],
           SPUAssemblyVersion_chars[1],
           SPUAssemblyVersion_chars[2],
           SPUAssemblyVersion_chars[3]);
}
References printf(), and SPU_VERSION.
Referenced by parseArgs().