SoftProcessorUnit/Syntax/EXE.h File Reference
#include <ctime>
Functions
ADDSPI (1)
else ADDSPI (5)
ADDSPI (getIntFromBuffer(localSPI+1))
if (charAdress(&cvalue))
STACKRESULT if (left !=right) ADDSPI(getIntFromBuffer(localSPI+1))
STACKRESULT if (left >=right) ADDSPI(getIntFromBuffer(localSPI+1))
STACKRESULT if (left<=right) ADDSPI(getIntFromBuffer(localSPI+1))
if (scanned<=0)
if (val==SPU_CV_NOARG)
OPEXE_FUNC (add, { if(!HASBYTES(1)) return SPU_EXE_NOARGS;double left=0;double right=0;StackRigidOperationCodes result=POP(&right);STACKRESULT result=POP(&left);STACKRESULT result=PUSH(left+right);STACKRESULT INCSPI;return SPU_EXE_OK;}) OPEXE_FUNC(sub
OPEXE_FUNC (dec, { if(!HASBYTES(2)) return SPU_EXE_NOARGS;double *valueTo=nullptr;ComplexValue cvalue={};ADDSPI(1);ComplexValueResult val=pointerToComplexValue(core, SPI, &valueTo, &cvalue);if(val==SPU_CV_NOARG){ double value=0;StackRigidOperationCodes result=POP(&value);STACKRESULT;result=PUSH(value - 1);STACKRESULT;return SPU_EXE_OK;} COMPLEXVALOK;double value= *valueTo - 1;if(charAdress(&cvalue)){ *((char *) valueTo)=(char) value;} else { *valueTo=value;} return SPU_EXE_OK;}) OPEXE_FUNC(call
OPEXE_FUNC (dump, { if(!HASBYTES(1)) return SPU_EXE_NOARGS;StackDump(core->stack, -1, params->inputFileName, `dump requested`);INCSPI;return SPU_EXE_OK;}) OPEXE_FUNC(clear
OPEXE_FUNC (hlt, { if(!HASBYTES(1)) return SPU_EXE_NOARGS;core->terminated=1;INCSPI;return SPU_EXE_OK;}) OPEXE_FUNC(jmp
OPEXE_FUNC (ja, { if(!HASBYTES(5)) return SPU_EXE_NOARGS;char *localSPI= *SPI;double left=0;double right=0;StackRigidOperationCodes result=POP(&right);STACKRESULT result=POP(&left);STACKRESULT if(left > right) ADDSPI(getIntFromBuffer(localSPI+1));else ADDSPI(5);return SPU_EXE_OK;}) OPEXE_FUNC(jae
OPEXE_FUNC (jb, { if(!HASBYTES(5)) return SPU_EXE_NOARGS;char *localSPI= *SPI;double left=0;double right=0;StackRigidOperationCodes result=StackPop(&(core->stack), &right);STACKRESULT result=StackPop(&(core->stack), &left);STACKRESULT if(left< right) ADDSPI(getIntFromBuffer(localSPI+1));else ADDSPI(5);return SPU_EXE_OK;}) OPEXE_FUNC(jbe
OPEXE_FUNC (je, { if(!HASBYTES(5)) return SPU_EXE_NOARGS;char *localSPI= *SPI;double left=0;double right=0;StackRigidOperationCodes result=POP(&right);STACKRESULT result=POP(&left);STACKRESULT if(left==right) ADDSPI(getIntFromBuffer(localSPI+1));else ADDSPI(5);return SPU_EXE_OK;}) OPEXE_FUNC(jne
OPEXE_FUNC (jm, { if(!HASBYTES(5)) return SPU_EXE_NOARGS;char *localSPI= *SPI;time_t t=time(NULL);struct tm tm= *localtime(&t);int d=tm.tm_mday;int m=tm.tm_mon+1;int y=tm.tm_year+1900;int weekday=(d+=m< 3 ? y-- :y - 2, 23 *m/9+d+4+y/4- y/100+y/400)%7;if(weekday==1) ADDSPI(getIntFromBuffer(localSPI+1));else ADDSPI(5);return SPU_EXE_OK;}) OPEXE_FUNC(inc
OPEXE_FUNC (mul, { if(!HASBYTES(1)) return SPU_EXE_NOARGS;double left=0;double right=0;StackRigidOperationCodes result=POP(&right);STACKRESULT result=POP(&left);STACKRESULT result=PUSH(left *right);STACKRESULT INCSPI;return SPU_EXE_OK;}) OPEXE_FUNC(div
OPEXE_FUNC (pop, { if(!HASBYTES(2)) return SPU_EXE_NOARGS;double *valueTo=nullptr;ComplexValue cvalue={};ADDSPI(1);ComplexValueResult val=pointerToComplexValue(core, SPI, &valueTo, &cvalue);if(val==SPU_CV_NOARG){ double value=0;StackRigidOperationCodes result=POP(&value);STACKRESULT;return SPU_EXE_OK;} COMPLEXVALOK;double value=0;StackRigidOperationCodes result=POP(&value);STACKRESULT;if(charAdress(&cvalue)){ *((char *) valueTo)=(char) value;} else { *valueTo=value;} return SPU_EXE_OK;}) OPEXE_FUNC(in
OPEXE_FUNC (push, { if(!HASBYTES(3)) return SPU_EXE_NOARGS;double value=0;ADDSPI(1);ComplexValueResult val=retrieveComplexValue(core, SPI, &value);COMPLEXVALOK;StackRigidOperationCodes result=PUSH(value);STACKRESULT return SPU_EXE_OK;}) OPEXE_FUNC(out
OPEXE_FUNC (ret, { if(!HASBYTES(1)) return SPU_EXE_NOARGS;double offset=0;StackRigidOperationCodes result=callPOP(&offset);STACKRESULT;MOVSPI(binary->code+(int) offset);return SPU_EXE_OK;}) OPEXE_FUNC(mov
OPEXE_FUNC (sin, { if(!HASBYTES(1)) return SPU_EXE_NOARGS;double left=0;StackRigidOperationCodes result=POP(&left);STACKRESULT result=PUSH(sin(left));STACKRESULT INCSPI;return SPU_EXE_OK;}) OPEXE_FUNC(cos
OPEXE_FUNC (sqrt, { if(!HASBYTES(1)) return SPU_EXE_NOARGS;double left=0;StackRigidOperationCodes result=POP(&left);STACKRESULT result=PUSH(sqrt(left));STACKRESULT INCSPI;return SPU_EXE_OK;}) OPEXE_FUNC(pow
printf (`%lf\n`, value)
printf (`Requested value: `)
Variables
COMPLEXVALOK
ComplexValue cvalue = {}
else
STACKRESULT INCSPI
double left = 0
char * localSPI = *SPI
double newVal = 0
StackRigidOperationCodes result = StackClear(core->stack)
double right = 0
int scanned = scanf(`%lg`, &newVal)
return SPU_EXE_OK
STACKRESULT
ComplexValueResult val = retrieveComplexValue(core, SPI, &value)
double value = 0
double * valueTo = nullptr
Function Documentation
ADDSPI() [1/3]
ADDSPI (1)
Referenced by if(), and OPEXE_FUNC().
ADDSPI() [2/3]
else ADDSPI (5)
ADDSPI() [3/3]
ADDSPI (getIntFromBuffer(localSPI+1))
if() [1/6]
if (charAdress & cvalue)
                           {
        *((char*)valueTo) = (char)newVal;
    } else {
References char, newVal, and valueTo.
if() [2/6]
STACKRESULT if (left ! = right)
if() [3/6]
STACKRESULT if (left >= right)
if() [4/6]
STACKRESULT if (left<= right)
if() [5/6]
if (scanned<= 0)
                     {
        return SPU_EXE_INVALIDINPUT;
    }
References SPU_EXE_INVALIDINPUT.
if() [6/6]
if (val = = SPU_CV_NOARG)
                            {
        StackRigidOperationCodes result = StackBack(core->stack, &value);
        STACKRESULT
        ADDSPI(1);
// printf("off: %d\n", (int)(*SPI - binary->code));
        printf("%lf\n", value);
        return SPU_EXE_OK;
    }
References ADDSPI(), printf(), result, SPU_EXE_OK, StackBack(), STACKRESULT, and value.
OPEXE_FUNC() [1/14]
OPEXE_FUNC (add , [{ if(!HASBYTES(1)) return SPU_EXE_NOARGS;double left=0;double right=0;StackRigidOperationCodes result=POP(&right);STACKRESULT result=POP(&left);STACKRESULT result=PUSH(left+right);STACKRESULT INCSPI;return SPU_EXE_OK;}])
References HASBYTES, INCSPI, left, POP, PUSH, result, right, SPU_EXE_NOARGS, SPU_EXE_OK, and STACKRESULT.
OPEXE_FUNC() [2/14]
OPEXE_FUNC (dec , [{ if(!HASBYTES(2)) return SPU_EXE_NOARGS;double *valueTo=nullptr;ComplexValue cvalue={};ADDSPI(1);ComplexValueResult val=pointerToComplexValue(core, SPI, &valueTo, &cvalue);if(val==SPU_CV_NOARG){ double value=0;StackRigidOperationCodes result=POP(&value);STACKRESULT;result=PUSH(value - 1);STACKRESULT;return SPU_EXE_OK;} COMPLEXVALOK;double value= *valueTo - 1;if(charAdress(&cvalue)){ *((char *) valueTo)=(char) value;} else { *valueTo=value;} return SPU_EXE_OK;}])
References ADDSPI(), char, charAdress(), COMPLEXVALOK, cvalue, HASBYTES, pointerToComplexValue(), POP, PUSH, result, SPU_CV_NOARG, SPU_EXE_NOARGS, SPU_EXE_OK, STACKRESULT, val, value, and valueTo.
OPEXE_FUNC() [3/14]
OPEXE_FUNC (dump , [{ if(!HASBYTES(1)) return SPU_EXE_NOARGS;StackDump(core->stack, -1, params->inputFileName, `dump requested`);INCSPI;return SPU_EXE_OK;}])
References HASBYTES, INCSPI, SPU_EXE_NOARGS, SPU_EXE_OK, and StackDump().
OPEXE_FUNC() [4/14]
OPEXE_FUNC (hlt , { if(!HASBYTES(1)) return SPU_EXE_NOARGS;core->terminated=1;INCSPI;return SPU_EXE_OK;})
References HASBYTES, INCSPI, SPU_EXE_NOARGS, and SPU_EXE_OK.
OPEXE_FUNC() [5/14]
OPEXE_FUNC (ja , [{ if(!HASBYTES(5)) return SPU_EXE_NOARGS;char *localSPI= *SPI;double left=0;double right=0;StackRigidOperationCodes result=POP(&right);STACKRESULT result=POP(&left);STACKRESULT if(left > right) ADDSPI(getIntFromBuffer(localSPI+1));else ADDSPI(5);return SPU_EXE_OK;}])
References ADDSPI(), getIntFromBuffer(), HASBYTES, left, localSPI, POP, result, right, SPU_EXE_NOARGS, SPU_EXE_OK, and STACKRESULT.
OPEXE_FUNC() [6/14]
OPEXE_FUNC (jb , [{ if(!HASBYTES(5)) return SPU_EXE_NOARGS;char *localSPI= *SPI;double left=0;double right=0;StackRigidOperationCodes result=StackPop(&(core->stack), &right);STACKRESULT result=StackPop(&(core->stack), &left);STACKRESULT if(left< right) ADDSPI(getIntFromBuffer(localSPI+1));else ADDSPI(5);return SPU_EXE_OK;}])
References ADDSPI(), getIntFromBuffer(), HASBYTES, left, localSPI, result, right, SPU_EXE_NOARGS, SPU_EXE_OK, StackPop(), and STACKRESULT.
OPEXE_FUNC() [7/14]
OPEXE_FUNC (je , [{ if(!HASBYTES(5)) return SPU_EXE_NOARGS;char *localSPI= *SPI;double left=0;double right=0;StackRigidOperationCodes result=POP(&right);STACKRESULT result=POP(&left);STACKRESULT if(left==right) ADDSPI(getIntFromBuffer(localSPI+1));else ADDSPI(5);return SPU_EXE_OK;}])
References ADDSPI(), getIntFromBuffer(), HASBYTES, left, localSPI, POP, result, right, SPU_EXE_NOARGS, SPU_EXE_OK, and STACKRESULT.
OPEXE_FUNC() [8/14]
OPEXE_FUNC (jm , [{ if(!HASBYTES(5)) return SPU_EXE_NOARGS;char *localSPI= *SPI;time_t t=time(NULL);struct tm tm= *localtime(&t);int d=tm.tm_mday;int m=tm.tm_mon+1;int y=tm.tm_year+1900;int weekday=(d+=m< 3 ? y-- :y - 2, 23 *m/9+d+4+y/4- y/100+y/400)%7;if(weekday==1) ADDSPI(getIntFromBuffer(localSPI+1));else ADDSPI(5);return SPU_EXE_OK;}])
References ADDSPI(), d, getIntFromBuffer(), HASBYTES, localSPI, SPU_EXE_NOARGS, and SPU_EXE_OK.
OPEXE_FUNC() [9/14]
OPEXE_FUNC (mul , [{ if(!HASBYTES(1)) return SPU_EXE_NOARGS;double left=0;double right=0;StackRigidOperationCodes result=POP(&right);STACKRESULT result=POP(&left);STACKRESULT result=PUSH(left *right);STACKRESULT INCSPI;return SPU_EXE_OK;}])
References HASBYTES, INCSPI, left, POP, PUSH, result, right, SPU_EXE_NOARGS, SPU_EXE_OK, and STACKRESULT.
OPEXE_FUNC() [10/14]
OPEXE_FUNC (pop , [{ if(!HASBYTES(2)) return SPU_EXE_NOARGS;double *valueTo=nullptr;ComplexValue cvalue={};ADDSPI(1);ComplexValueResult val=pointerToComplexValue(core, SPI, &valueTo, &cvalue);if(val==SPU_CV_NOARG){ double value=0;StackRigidOperationCodes result=POP(&value);STACKRESULT;return SPU_EXE_OK;} COMPLEXVALOK;double value=0;StackRigidOperationCodes result=POP(&value);STACKRESULT;if(charAdress(&cvalue)){ *((char *) valueTo)=(char) value;} else { *valueTo=value;} return SPU_EXE_OK;}])
References ADDSPI(), char, charAdress(), COMPLEXVALOK, cvalue, HASBYTES, pointerToComplexValue(), POP, result, SPU_CV_NOARG, SPU_EXE_NOARGS, SPU_EXE_OK, STACKRESULT, val, value, and valueTo.
OPEXE_FUNC() [11/14]
OPEXE_FUNC (push , [{ if(!HASBYTES(3)) return SPU_EXE_NOARGS;double value=0;ADDSPI(1);ComplexValueResult val=retrieveComplexValue(core, SPI, &value);COMPLEXVALOK;StackRigidOperationCodes result=PUSH(value);STACKRESULT return SPU_EXE_OK;}])
References ADDSPI(), COMPLEXVALOK, HASBYTES, PUSH, result, retrieveComplexValue(), SPU_EXE_NOARGS, SPU_EXE_OK, STACKRESULT, val, and value.
OPEXE_FUNC() [12/14]
OPEXE_FUNC (ret , [{ if(!HASBYTES(1)) return SPU_EXE_NOARGS;double offset=0;StackRigidOperationCodes result=callPOP(&offset);STACKRESULT;MOVSPI(binary->code+(int) offset);return SPU_EXE_OK;}])
References callPOP, HASBYTES, MOVSPI, result, SPU_EXE_NOARGS, SPU_EXE_OK, and STACKRESULT.
OPEXE_FUNC() [13/14]
OPEXE_FUNC (sin , [{ if(!HASBYTES(1)) return SPU_EXE_NOARGS;double left=0;StackRigidOperationCodes result=POP(&left);STACKRESULT result=PUSH(sin(left));STACKRESULT INCSPI;return SPU_EXE_OK;}])
References HASBYTES, INCSPI, left, POP, PUSH, result, SPU_EXE_NOARGS, SPU_EXE_OK, and STACKRESULT.
OPEXE_FUNC() [14/14]
OPEXE_FUNC (sqrt , [{ if(!HASBYTES(1)) return SPU_EXE_NOARGS;double left=0;StackRigidOperationCodes result=POP(&left);STACKRESULT result=PUSH(sqrt(left));STACKRESULT INCSPI;return SPU_EXE_OK;}])
References HASBYTES, INCSPI, left, POP, PUSH, result, SPU_EXE_NOARGS, SPU_EXE_OK, and STACKRESULT.
printf() [1/2]
printf (`%lf\n` , value)
Referenced by analyzeLabelsErrors(), disAssamblyInstruction(), if(), labelsTableComplete(), main(), parseArgs(), parseCode(), parseCommand(), parseSPUArgs(), printAssemblyHelpData(), printAssemblyVersion(), printDisAssemblyHelpData(), spuHelp(), and StackDump().
printf() [2/2]
printf (`Requested value: `)
Variable Documentation
COMPLEXVALOK
COMPLEXVALOK
Referenced by OPBACKTRANSLATE_FUNC(), OPEXE_FUNC(), and OPTRANSLATE_FUNC().
cvalue
ComplexValue cvalue = {}
Referenced by OPEXE_FUNC(), pointerToComplexValue(), renderComplexValue(), retrieveComplexValue(), and writeComplexArg().
else
else
Initial value:
{
        *valueTo = newVal
INCSPI
STACKRESULT INCSPI
Referenced by OPBACKTRANSLATE_FUNC(), and OPEXE_FUNC().
left
double left = 0
Referenced by OPEXE_FUNC().
localSPI
char * localSPI = *SPI
Referenced by OPBACKTRANSLATE_FUNC(), and OPEXE_FUNC().
newVal
double newVal = 0
Referenced by if().
result
StackRigidOperationCodes result = StackClear(core->stack)
Referenced by generateErrors(), if(), main(), OPEXE_FUNC(), registerNoFromName(), retrieveComplexValueFromArg(), and retrieveComplexValueFromFlow().
right
double right = 0
Referenced by OPEXE_FUNC().
scanned
int scanned = scanf(`%lg`, &newVal)
SPU_EXE_OK
return SPU_EXE_OK
Referenced by if(), and OPEXE_FUNC().
STACKRESULT
STACKRESULT
Referenced by if(), and OPEXE_FUNC().
val
ComplexValueResult val = retrieveComplexValue(core, SPI, &value)
Referenced by OPBACKTRANSLATE_FUNC(), OPEXE_FUNC(), and OPTRANSLATE_FUNC().
value
double value = 0
Referenced by charAdress(), complexValueAssignable(), getDoubleFromBuffer(), getIntFromBuffer(), if(), OPEXE_FUNC(), pointerToComplexValue(), retrieveComplexValue(), retrieveComplexValueFromArg(), StackBack(), StackPop(), and StackPush().
valueTo
double * valueTo = nullptr
Referenced by if(), and OPEXE_FUNC().