SoftProcessorUnit/Syntax/Translation/Helpers/ParseHelpers.hpp File Reference
Functions
double getDoubleFromBuffer (char *start)
int getIntFromBuffer (char *start)
Function Documentation
getDoubleFromBuffer()
double getDoubleFromBuffer (char * start)
                                        {
    double value = 0;
    memcpy(&value, start, sizeof(double));
    return value;
}
Referenced by OPBACKTRANSLATE_FUNC(), and OPEXE_FUNC().
getIntFromBuffer()
int getIntFromBuffer (char * start)
                                  {
    int value = 0;
    memcpy(&value, start, sizeof(int));
    return value;
}
Referenced by OPEXE_FUNC().