SoftProcessorUnit/SPU/Core/SPUCore.cpp File Reference
#include `SPUCore.hpp`
#include `INFO.h`
Macros
#define CALLEXE(name) return name (core, params, binary, SPI)
#define COMMAND_INFO(name, code, args, flags, isValue) case code : EVALUATE(CALLEXE(EVALUATE(CMDEXE_ ## name)));
#define EVALUATE(a) a
Functions
void ConstructSPUCore (SPUCore *core, size_t initStackSize)
void DestructSPUCore (SPUCore *core)
InstructionExeResult executeInstruction (SPUCore *core, RunParameters *params, BinaryFile *binary, char **SPI)
InstructionExeResult runCode (SPUCore *core, RunParameters *params, BinaryFile *binary)
Macro Definition Documentation
CALLEXE
#define CALLEXE(name) return name (core, params, binary, SPI)
COMMAND_INFO
#define COMMAND_INFO(name, code, args, flags, isValue) case code : EVALUATE(CALLEXE(EVALUATE(CMDEXE_ ## name)));
EVALUATE
#define EVALUATE(a) a
Function Documentation
ConstructSPUCore()
void ConstructSPUCore (SPUCore * core, size_t initStackSize)
                                                           {
    core->stack = NewStackRigid_double(initStackSize, stderr);
    core->callStack = NewStackRigid_double(16, stderr);
    core->terminated = 0;
}
References SPUCore::callStack, SPUCore::stack, and SPUCore::terminated.
Referenced by main().
DestructSPUCore()
void DestructSPUCore (SPUCore * core)
                                    {
    StackDestruct(&(core->stack));
    StackDestruct(&(core->callStack));
}
References SPUCore::callStack, SPUCore::stack, and StackDestruct().
Referenced by main().
executeInstruction()
InstructionExeResult executeInstruction (SPUCore * core, RunParameters * params, BinaryFile * binary, char ** SPI)
                                                    {
// printf("NOW: %d\n", binary->codeOffset + (int)(*SPI - binary->code));
    switch (**SPI) {
        #define COMMAND_INFO(name, code, args, flags, isValue) case code : EVALUATE(CALLEXE(EVALUATE(CMDEXE_ ## name)));
            
        #include "INFO.h"
            
        #undef COMMAND_INFO
            
        default:
            return SPU_EXE_UNKNOWN;
    }
}
References SPU_EXE_UNKNOWN.
Referenced by runCode().
runCode()
InstructionExeResult runCode (SPUCore * core, RunParameters * params, BinaryFile * binary)
                                                                                       {
    core->terminated = 0;
    
    char* SPI = binary->code;
    
    while (!core->terminated && SPI < binary->code + binary->currentSize) {
        char* prevOffset = SPI;
        InstructionExeResult cmdResult = executeInstruction(core, params, binary, &SPI);
        if (cmdResult != SPU_EXE_OK){
            core->terminated = 1;
            fprintf(stderr, "error: spu: terminated at offset: %d reached: %d\n",
                    (int)((int)(prevOffset - binary->code) + (int)(binary->codeOffset)), (int)((int)(SPI - binary->code) + (int)(binary->codeOffset)));
            return cmdResult;
        }
    }
    
    return SPU_EXE_OK;
}
References BinaryFile::code, BinaryFile::codeOffset, BinaryFile::currentSize, executeInstruction(), SPU_EXE_OK, and SPUCore::terminated.
Referenced by main().