SoftProcessorUnit/SPU/Core/SPUCore.hpp File Reference
#include <cstdio>
#include `Syntax.hpp`
#include `SPUDtypes.hpp`
#include `StackRigid.h`
#include `CommandsParser.hpp`
#include `CommandsDTypes.hpp`
#include `InstrExecutors.hpp`
Functions
void ConstructSPUCore (SPUCore *core, size_t initStackSize)
void DestructSPUCore (SPUCore *core)
InstructionExeResult executeInstruction (SPUCore *core, RunParameters *params, BinaryFile *binary, char **SPI)
InstructionExeResult runCode (SPUCore *core, RunParameters *params, BinaryFile *binary)
Function Documentation
ConstructSPUCore()
void ConstructSPUCore (SPUCore * core, size_t initStackSize)
                                                           {
    core->stack = NewStackRigid_double(initStackSize, stderr);
    core->callStack = NewStackRigid_double(16, stderr);
    core->terminated = 0;
    fillBlank(core);
}
References SPUCore::callStack, fillBlank(), SPUCore::stack, and SPUCore::terminated.
Referenced by main().
DestructSPUCore()
void DestructSPUCore (SPUCore * core)
                                    {
    StackDestruct(&(core->stack));
    StackDestruct(&(core->callStack));
}
References SPUCore::callStack, SPUCore::stack, and StackDestruct().
Referenced by main().
executeInstruction()
InstructionExeResult executeInstruction (SPUCore * core, RunParameters * params, BinaryFile * binary, char ** SPI)
                                                    {
// printf("NOW: %d\n", binary->codeOffset + (int)(*SPI - binary->code));
    switch (**SPI) {
        #define COMMAND_INFO(name, code, args, flags, isValue) case code : EVALUATE(CALLEXE(EVALUATE(CMDEXE_ ## name)));
            
        #include "INFO.h"
            
        #undef COMMAND_INFO
            
        default:
            return SPU_EXE_UNKNOWN;
    }
}
References SPU_EXE_UNKNOWN.
Referenced by runCode().
runCode()
InstructionExeResult runCode (SPUCore * core, RunParameters * params, BinaryFile * binary)
                                                                                       {
    core->terminated = 0;
    
    char* SPI = binary->code;
    
    while (!core->terminated && SPI < binary->code + binary->currentSize) {
        char* prevOffset = SPI;
        InstructionExeResult cmdResult = executeInstruction(core, params, binary, &SPI);
        if (cmdResult != SPU_EXE_OK){
            core->terminated = 1;
            fprintf(stderr, "error: spu: terminated at offset: %d reached: %d\n",
                    (int)((int)(prevOffset - binary->code) + (int)(binary->codeOffset)), (int)((int)(SPI - binary->code) + (int)(binary->codeOffset)));
            return cmdResult;
        }
        if (params->vsync){
            renderVRAM(core);
        }
    }
    
    return SPU_EXE_OK;
}
References BinaryFile::code, BinaryFile::codeOffset, BinaryFile::currentSize, executeInstruction(), renderVRAM(), SPU_EXE_OK, SPUCore::terminated, and RunParameters::vsync.
Referenced by main().