SoftProcessorUnit/Common/Stack/StackRigid.cpp File Reference
#include <stdio.h>
#include `StackRigid.h`
#include <stdlib.h>
#include <assert.h>
#include <time.h>
Macros
#define IGNORE_VALIDITY
#define StackDumpWrapper(stack) { StackDump(stack, __LINE__, __FILE__, ``); }
#define StackDumpWrapperWhy(stack, why) { StackDump(stack, __LINE__, __FILE__, why); }
Functions
__overload (StackRigid) *__overload(NewStackRigid)(const size_t capacity = (__overload(StackRigid)*)calloc(memory, 1)
Create new stack with pre-defined capacity.
static unsigned long __StackGetChecksum (__overload(StackRigid) *stack)
Claculates big Stack checksum. Uses Adler-32 method.
static unsigned long __StackGetChecksumVital (__overload(StackRigid) *stack)
Uses Adler-32 method. Calculates Stack checksum only for the vital parameters. This is necessary because __StackGetChecksum() relies on capacity and size. If they were changed, behaviour is undefined.
static StackRigidOperationCodes __StackReallocate (__overload(StackRigid) **stack, short int direction)
Reallocates Stack if needed.
static void __StackUpdateChecksum (__overload(StackRigid) *stack)
Updates Stack checksums. Does not take into account bytes inside the stack but outside of its last element.
__StackUpdateChecksum (pointer)
static unsigned long adlerChecksum (const void *firstBlock, size_t len)
Calculates Adler-32 checksum from the firstBlock to the firstBlock + len.
if (!istack_pointer_valid(logFile, sizeof(logFile)))
if (!istack_pointer_valid(pointer, sizeof(pointer)))
if (added< memory)
static bool istack_pointer_valid (void *addr, int size)
Checks for pointer validity.
StackRigidOperationCodes StackBack (__overload(StackRigid) *stack, StackElementType *value)
Free stack memory.
StackRigidOperationCodes StackClear (__overload(StackRigid) *stack)
Clear the stack.
StackRigidOperationCodes StackDestruct (__overload(StackRigid) **stack)
Free stack memory.
void StackDump (__overload(StackRigid) *stack, const int line, const char *file, const char *why)
Dumps debug information about the stack.
StackRigidOperationCodes StackPop (__overload(StackRigid) **stack, StackElementType *value)
Pop value from the end of the stack The operation can perform reallocations if there is too much space.
StackRigidOperationCodes StackPush (__overload(StackRigid) **stack, StackElementType value)
Push the value to the stack The operation can perform reallocations if there is not enough space.
size_t StackRigidMemoryUse (__overload(StackRigid) *stack)
Memory alocated for the Stack.
StackRigidState StackValidate (__overload(StackRigid) *stack)
Perform all stack checks: checksums, general constrains.
Variables
size_t added = memory + (capacity - 1) * sizeof(StackElementType)
pointer capacity = capacity
pointer checkSum = 0
pointer checkSumVital = 0
FILE * logFile
size_t memory = sizeof(__overload(StackRigid))
return pointer
pointer size = 0
Macro Definition Documentation
IGNORE_VALIDITY
#define IGNORE_VALIDITY
StackDumpWrapper
#define StackDumpWrapper(stack) { StackDump(stack, __LINE__, __FILE__, ``); }
StackDumpWrapperWhy
#define StackDumpWrapperWhy(stack, why) { StackDump(stack, __LINE__, __FILE__, why); }
Function Documentation
__overload()
__overload (StackRigid) const = (__overload(StackRigid)*)calloc(memory, 1)
Create new stack with pre-defined capacity.
Parameters
 in capacity initial stack capacity. Set to 0 if you want the stack to adopt automaticaly.
 in,out logFile file for logging
Returns
new stack pointer or NULL if impossible
Referenced by __StackReallocate(), StackDump(), and StackRigidMemoryUse().
__StackGetChecksum()
static unsigned long __StackGetChecksum (__overload(StackRigid) * stack) [static]
Claculates big Stack checksum. Uses Adler-32 method.
Attention
Not for the manual use!
* Stack memory : [ checkSum checkSumVital capacity size logFile | value 1, value 2, ..., value n || ___garbage area___]
* Release:
* ________________from here ^__________________________________________________________^to here
* Debug:
* ________________from here ^______________________________________________________________________________^to here
* 
Parameters
 in stack Stack that checksums are needed to be updated
                                                                        {
    assert(stack);
    
    void* firstBlock = (char*)stack + sizeof(stack->checkSum);
    
    // Memory used by Stack excluding checkSum and free space
    #ifndef DEBUG
        const size_t memory = StackRigidMemoryUse(stack) - sizeof(stack->checkSum) - (stack->capacity - stack->size) * sizeof(StackElementType);
    #endif
    #ifdef DEBUG
        const size_t memory = StackRigidMemoryUse(stack) - sizeof(stack->checkSum);
    #endif
    
    if (stack->size > stack->capacity) {
        return 0;
    }
    return adlerChecksum(firstBlock, memory);
}
References adlerChecksum(), memory, StackElementType, and StackRigidMemoryUse().
Referenced by __StackUpdateChecksum(), and StackValidate().
__StackGetChecksumVital()
static unsigned long __StackGetChecksumVital (__overload(StackRigid) * stack) [static]
Uses Adler-32 method. Calculates Stack checksum only for the vital parameters. This is necessary because __StackGetChecksum() relies on capacity and size. If they were changed, behaviour is undefined.
Attention
Not for the manual use!
* Stack memory : [ checkSum checkSumVital capacity size logFile | value 1, value 2, ..., value n || ___garbage area___]
* ______________________________from here ^__________________^to here
* 
Parameters
 in stack Stack that checksums are needed to be updated
                                                                             {
    assert(stack);
    
    void* firstBlock = (char*)stack + sizeof(stack->checkSum) + sizeof(stack->checkSumVital);
    
    const size_t memory = (size_t)((char*)(stack->data) - (char*)firstBlock);
    if (stack->size > stack->capacity) {
        return 0;
    }
    return adlerChecksum(firstBlock, memory);
}
References adlerChecksum(), and memory.
Referenced by __StackUpdateChecksum(), and StackValidate().
__StackReallocate()
static StackRigidOperationCodes __StackReallocate (__overload(StackRigid) ** stack, short int direction) [static]
Reallocates Stack if needed.
Attention
Not for the manual use!
Parameters
 in,out stack Stack to be reallocated
 in direction which direction reallocations are available. > 0 -> expand space if needed, < 0 -> shrink space if needed
                                                                                                        {
    if ((*stack)->capacity == 0) {
        (*stack)->capacity = 16; // capacity if was 0
        
        const size_t memory = StackRigidMemoryUse(*stack);
        
         __overload(StackRigid)* newStack = (__overload(StackRigid)*) realloc((*stack), memory);
        if (!istack_pointer_valid(newStack, sizeof(newStack))){
            if (newStack != NULL)
                free(newStack);
            return STACK_OP_NOMEMORY;
        }
        
        (*stack) = newStack;
    }else if(((*stack)->capacity <= (*stack)->size) && direction > 0) { // Up reallocation
        size_t newCapacity = (*stack)->size * 2;
        
        if (newCapacity <= (*stack)->size) { // If we exceeded size_t range
            newCapacity = (*stack)->size + 16; // Try to add 16 free spaces
            if (newCapacity < (*stack)->size) // Even if in this case we still exceed size_t
                return STACK_OP_OVERFLOW;
        }
        
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        const size_t memoryNew = sizeof(__overload(StackRigid)) + (newCapacity - 1) * sizeof(StackElementType);
        
        if (memoryNew >= memoryNow) {
             __overload(StackRigid)* newStack = (__overload(StackRigid)*) realloc((*stack), memoryNew);
            if (!istack_pointer_valid(newStack, sizeof(newStack)))
                return STACK_OP_NOMEMORY;
            
            (*stack) = newStack;
        }else{
            return STACK_OP_OVERFLOW; // Exceded size_t memory
        }
        (*stack)->capacity = newCapacity;
        
    }else if (((*stack)->capacity / 2.2 > (*stack)->size) && direction < 0) { // Down reallocation
        size_t newCapacity = (size_t)((*stack)->capacity / 2.2);
        
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        const size_t memoryNew = sizeof(__overload(StackRigid)) + (newCapacity - 1) * sizeof(StackElementType);
        
        if (memoryNew <= memoryNow) {
             __overload(StackRigid)* newStack = (__overload(StackRigid)*) realloc((*stack), memoryNew);
            if (!istack_pointer_valid(newStack, sizeof(newStack))){
                if (newStack != NULL) {
                    free(newStack);
                    free((*stack));
                }
                return STACK_OP_NOMEMORY;
            }
            
            (*stack) = newStack;
            (*stack)->capacity = newCapacity;
        }else
            return STACK_OP_OVERFLOW; // Exceded size_t memory
    }
    return STACK_OP_OK;
}
References __overload(), istack_pointer_valid(), memory, STACK_OP_NOMEMORY, STACK_OP_OK, STACK_OP_OVERFLOW, StackElementType, and StackRigidMemoryUse().
Referenced by StackPop(), and StackPush().
__StackUpdateChecksum() [1/2]
static void __StackUpdateChecksum (__overload(StackRigid) * stack) [static]
Updates Stack checksums. Does not take into account bytes inside the stack but outside of its last element.
Attention
Not for the manual use!
* Stack memory :  [ __stack area__ | value 1, value 2, ..., value n || ___garbage area___]
* ____________________________________________________________________^ alterations in this area are not checked
* 
Parameters
 in,out stack Stack that checksums are needed to be updated
                                                                  {
    assert(stack);
    #ifndef IGNORE_VALIDITY
        stack->checkSumVital = __StackGetChecksumVital(stack);
        stack->checkSum = __StackGetChecksum(stack);
    #endif
}
References __StackGetChecksum(), and __StackGetChecksumVital().
Referenced by StackPop(), and StackPush().
__StackUpdateChecksum() [2/2]
__StackUpdateChecksum (pointer)
adlerChecksum()
static unsigned long adlerChecksum (const void * firstBlock, size_t len) [static]
Calculates Adler-32 checksum from the firstBlock to the firstBlock + len.
Attention
Not for the manual use!
Parameters
 in firstBlock first block to include to the checksum
 in len length of byte sequence
Returns
checksum
                                                                       {
    unsigned long a = 1, b = 0;
    const unsigned long MOD_ADLER = 65521;
    for (size_t index = 0; index < len; ++index) {
        a = (a + ((unsigned char*)firstBlock)[index]) % MOD_ADLER;
        b = (b + a) % MOD_ADLER;
    }
    return (b << 16) | a;
}
Referenced by __StackGetChecksum(), and __StackGetChecksumVital().
if() [1/3]
if (! istack_pointer_validlogFile, sizeof(logFile))
                                                          {
         return NULL;
     }
if() [2/3]
if (! istack_pointer_validpointer, sizeof(pointer))
                                                         {
        if (pointer != NULL)
            free(pointer);
        return NULL;
    }
References pointer.
if() [3/3]
if ()
                         {
         return NULL;
     }
istack_pointer_valid()
static bool istack_pointer_valid (void * addr, int size) [static]
Checks for pointer validity.
Attention
Adjust this for your OS to increase security!
Parameters
 in addr address to be checked
 in size of the address
Returns
checksum
                                                       {
    if ((unsigned long long)addr < 4096 || (unsigned long long)addr % (unsigned long long)size != 0) {
        return false;
    }
    return true;
}
References size.
Referenced by __StackReallocate(), StackBack(), StackClear(), StackDestruct(), StackDump(), StackPop(), StackPush(), and StackValidate().
StackBack()
StackRigidOperationCodes StackBack (__overload(StackRigid) * stack, StackElementType * value)
Free stack memory.
Parameters
 out stack Stack to be used
Returns
the outcome of the operation
                                                                                           {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_NULL;
    
    
    StackRigidState integrityChecks = StackValidate(stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(stack, "StackBack operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    if(stack->size == 0)
        return STACK_OP_UNDERFLOW;
    
    *value = stack->data[stack->size - 1];
    return STACK_OP_OK;
}
References istack_pointer_valid(), STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by OPEXE_FUNC().
StackClear()
StackRigidOperationCodes StackClear (__overload(StackRigid) * stack)
Clear the stack.
Parameters
 in,out stack Stack to be changed
Returns
the outcome of the operation
                                                                   {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_NULL;
    
    
    StackRigidState integrityChecks = StackValidate(stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(stack, "StackClear operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    stack->size = 0;
    
    return STACK_OP_OK;
}
References istack_pointer_valid(), STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by OPEXE_FUNC().
StackDestruct()
StackRigidOperationCodes StackDestruct (__overload(StackRigid) ** stack)
Free stack memory.
Parameters
 in,out stack Stack to be distructed
Returns
the outcome of the operation
                                                                        {
    if (!istack_pointer_valid(stack, sizeof(stack))) {
        return STACK_OP_NULL;
    }
    if (!istack_pointer_valid(*stack, sizeof(*stack))) {
        return STACK_OP_NULL;
    }
    StackRigidState checks = StackValidate(*stack);
    if (checks == STACK_ST_OK){
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        for(char* cursor = (char*)(*stack); cursor < (char*)(*stack) + memoryNow; cursor++)
            *cursor = 0;
    }
    free(*stack);
    return STACK_OP_OK;
}
References istack_pointer_valid(), STACK_OP_NULL, STACK_OP_OK, STACK_ST_OK, StackRigidMemoryUse(), and StackValidate().
StackDump()
void StackDump (__overload(StackRigid) * stack, const int line, const char * file, const char * why)
Dumps debug information about the stack.
Parameters
 in stack Stack to be dumped
                                                                                                  {
    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wformat"
    time_t rawtime = time(NULL);
    struct tm *ptm = localtime(&rawtime);
    
    if (!istack_pointer_valid(stack, sizeof(stack))){
        fprintf(stdin, "\nStack dump is impossible: NULL pointer\n");
        return;
    }
    
    FILE* output = stack->logFile;
    if (!istack_pointer_valid(output, sizeof(output))) {
        output = stdout;
        printf("\nWarning! Specified dump output is inavailbale! Selecting stdout.\n");
    }
    
    fprintf(output, "=================================\n");
    fprintf(output, "Stack dump %s", asctime(ptm));
    fprintf(output, "Line: %d\nFile: %s\n", line, file);
    if (why[0] != '\0')
    fprintf(output, "Problem: %s\n", why);
    
    if (istack_pointer_valid(stack, sizeof(stack))) {
        fprintf(output, "Stack (");
        const char *status = "ok";
        StackRigidState checks = StackValidate(stack);
        switch (checks) {
            case STACK_ST_INTEGRITYERR:
                status = "INTEGRITY ERROR SPOTTED";
                break;
            case STACK_ST_UNINITIALIZED:
                status = "UNINITIALIZED";
                break;
            case STACK_ST_OK:
                status = "ok";
                break;
            case STACK_ST_NULL:
                status = "NULL POINTER";
                break;
        }
        fprintf(output, "%s", status);
        fprintf(output, ")");
        fprintf(output, " [%p]: {\n", (void*)stack);
        if (checks != STACK_ST_OK) {
            fprintf(output, "ERROR! Stack structure was corrupted.\nThe data below was changed from the outside.\nThis can fail!\n");
        }
        fprintf(output, "\t size : %lu\n", stack->size);
        fprintf(output, "\t capacity : %lu\n", stack->capacity);
        fprintf(output, "\t checkSum : %lx\n", stack->checkSumVital);
        fprintf(output, "\tcheckSumVital : %lx\n", stack->checkSum);
        
        fprintf(output, "\tdata [%p]: {\n", (void*)stack->data);
        if (checks == STACK_ST_OK) {
        size_t i = 0;
        for (i = 0; i < stack->size; i++) {
            fprintf(output, "\t\t");
            fprintf(output, "*[%lu] : ", i);
            fprintf(output, "[%p] ",(void*)(stack->data + i));
            StackElementDump(stack->logFile, stack->data[i]);
            fprintf(output, "\n");
        }
        fprintf(output, "\t\t _______\n");
        if (stack->size < stack->capacity) {
            fprintf(output, "\t\t [%lu] : GARBAGE(", i);
            fprintf(output, "[%p] ",(void*)(stack->data + i));
            StackElementDump(stack->logFile, stack->data[i]);
            fprintf(output, ")\n");
        }
        if (stack->size + 1< stack->capacity && stack->size + 1 > stack->size) {
            fprintf(output, "\t\t [%lu] : GARBAGE(", i + 1);
            fprintf(output, "[%p] ", (void*)(stack->data + i + 1));
            StackElementDump(stack->logFile, stack->data[i + 1]);
            fprintf(output, ")\n");
        }
        } else{
            fprintf(output, "\t\tDATA CAN'T BE READED\n");
        }
        
        fprintf(output, "\t}\n");
        fprintf(output, "}\n");
        
        const size_t memory = StackRigidMemoryUse(stack);
        fprintf(output, "Size allocated : %lu bytes\n", memory);
        fprintf(output, "Raw Stack size : %lu bytes\n", sizeof(__overload(StackRigid)));
        fprintf(output, " Element size : %lu bytes\n", sizeof(StackElementType));
        fprintf(output, " Block end : %p\n", (void*)((char*)stack + memory));
    }
    fprintf(output, "=================================\n");
    fflush(NULL);
    #pragma clang diagnostic pop
}
References __overload(), i, istack_pointer_valid(), memory, STACK_ST_INTEGRITYERR, STACK_ST_NULL, STACK_ST_OK, STACK_ST_UNINITIALIZED, StackElementDump, StackElementType, StackRigidMemoryUse(), and StackValidate().
Referenced by main().
StackPop()
StackRigidOperationCodes StackPop (__overload(StackRigid) ** stack, StackElementType * value)
Pop value from the end of the stack The operation can perform reallocations if there is too much space.
Parameters
 in,out stack Stack to be distructed
 out value value to be pushed
Returns
the outcome of the operation
                                                                                            {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_NULL;
    
    StackRigidState integrityChecks = StackValidate(*stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(*stack, "StackPop operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    if((*stack)->size == 0)
        return STACK_OP_UNDERFLOW;
    
    *value = (*stack)->data[(*stack)->size - 1];
    (*stack)->size -= 1;
    
    StackRigidOperationCodes realocRes = __StackReallocate(stack, -1);
    if (realocRes == STACK_OP_OK)
        __StackUpdateChecksum(*stack);
    else
        return realocRes;
    
    return STACK_OP_OK;
}
References __StackReallocate(), __StackUpdateChecksum(), istack_pointer_valid(), STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by OPEXE_FUNC().
StackPush()
StackRigidOperationCodes StackPush (__overload(StackRigid) ** stack, StackElementType value)
Push the value to the stack The operation can perform reallocations if there is not enough space.
Parameters
 in,out stack Stack to be changed
 in value value to be pushed
Returns
the outcome of the operation
                                                                                           {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_PTRINVALID;
    if (!istack_pointer_valid(*stack, sizeof(*stack)))
        return STACK_OP_PTRINVALID;
    
    
    StackRigidState integrityChecks = StackValidate(*stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(*stack, "StackPush operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    
    StackRigidOperationCodes reallocResult = __StackReallocate(stack, 1);
    
    if (reallocResult != STACK_OP_OK) {
        StackDumpWrapperWhy(*stack, "StackPop operation spotted integrity error during the reallocation");
        return reallocResult;
    }
    
    (*stack)->data[(*stack)->size] = value;
    (*stack)->size += 1;
    
    __StackUpdateChecksum(*stack);
    
    if ((*stack)->size == 0) {
        return STACK_OP_OVERFLOW;
    }
    return STACK_OP_OK;
}
References __StackReallocate(), __StackUpdateChecksum(), istack_pointer_valid(), STACK_OP_INTEGRITYERR, STACK_OP_OK, STACK_OP_OVERFLOW, STACK_OP_PTRINVALID, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
StackRigidMemoryUse()
size_t StackRigidMemoryUse (__overload(StackRigid) * stack)
Memory alocated for the Stack.
Parameters
 in stack Stack to be checked
Returns
alocated bytes
                                                           {
    assert(stack);
    return sizeof(__overload(StackRigid)) + (stack->capacity - 1) * sizeof(StackElementType);
}
References __overload(), and StackElementType.
Referenced by __StackGetChecksum(), __StackReallocate(), StackDestruct(), and StackDump().
StackValidate()
StackRigidState StackValidate (__overload(StackRigid) * stack)
Perform all stack checks: checksums, general constrains.
Parameters
 in stack Stack to be validated
Returns
calculated state
                                                              {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_ST_NULL;
    
    #ifdef IGNORE_VALIDITY
        return STACK_ST_OK;
    #endif
    
    #ifndef IGNORE_VALIDITY
        if (stack->size > stack->capacity || stack->checkSum == 0 || stack->checkSumVital == 0)
            return STACK_ST_INTEGRITYERR;
    #endif
    #ifndef IGNORE_VALIDITY
        unsigned long currentChecksumVital = __StackGetChecksumVital(stack);
        if (currentChecksumVital != stack->checkSumVital || currentChecksumVital == 0)
            return STACK_ST_INTEGRITYERR;
        
        unsigned long currentChecksum = __StackGetChecksum(stack);
        if (currentChecksum != stack->checkSum || currentChecksum == 0)
            return STACK_ST_INTEGRITYERR;
    #endif
    return STACK_ST_OK;
}
References __StackGetChecksum(), __StackGetChecksumVital(), istack_pointer_valid(), STACK_ST_INTEGRITYERR, STACK_ST_NULL, and STACK_ST_OK.
Referenced by StackBack(), StackClear(), StackDestruct(), StackDump(), StackPop(), and StackPush().
Variable Documentation
added
size_t added = memory + (capacity - 1) * sizeof(StackElementType)
capacity
pointer capacity = capacity
checkSum
pointer checkSum = 0
checkSumVital
pointer checkSumVital = 0
logFile
pointer logFile
Initial value:
{
     if (capacity == 0)
         capacity = 1
memory
memory = sizeof(__overload(StackRigid))
Referenced by __StackGetChecksum(), __StackGetChecksumVital(), __StackReallocate(), and StackDump().
pointer
return pointer
Referenced by if().
size
pointer size = 0
Referenced by appendToBinFile(), flushBinFile(), istack_pointer_valid(), and loadBinFile().