SoftProcessorUnit/Common/Stack/StackRigid.h File Reference
#include <stdlib.h>
Macros
#define __overload(FUNC) EVALUATOR(FUNC, StackElementType)
#define EVALUATOR(x, y) PASTER(x,y)
#define IGNORE_VALIDITY
#define PASTER(x, y) x ## _ ## y
Default element dump instruction.
#define StackElementDump(FILE, VALUE) {fprintf(FILE, `%g`, VALUE);}
#define StackElementType double
Typedefs
typedef enum StackRigidOperationCodes StackRigidOperationCodes
Codes returned after operations on Stack.
typedef enum StackRigidState StackRigidState
Codes characterizing Stack state.
Enumerations
enum StackRigidOperationCodes {
STACK_OP_OK,
STACK_OP_UNDERFLOW,
STACK_OP_OVERFLOW,
STACK_OP_NOMEMORY,
STACK_OP_INTEGRITYERR,
STACK_OP_NULL,
STACK_OP_PTRINVALID
 }
Codes returned after operations on Stack.
enum StackRigidState { STACK_ST_OK,
STACK_ST_INTEGRITYERR,
STACK_ST_UNINITIALIZED,
STACK_ST_NULL
 }
Codes characterizing Stack state.
Functions
struct __overload (StackRigid)
The main StackRigid struct.
static unsigned long __StackGetChecksum (__overload(StackRigid) *stack)
Claculates big Stack checksum. Uses Adler-32 method.
static unsigned long __StackGetChecksumVital (__overload(StackRigid) *stack)
Uses Adler-32 method. Calculates Stack checksum only for the vital parameters. This is necessary because __StackGetChecksum() relies on capacity and size. If they were changed, behaviour is undefined.
static StackRigidOperationCodes __StackReallocate (__overload(StackRigid) **stack, short int direction)
Reallocates Stack if needed.
static void __StackUpdateChecksum (__overload(StackRigid) *stack)
Updates Stack checksums. Does not take into account bytes inside the stack but outside of its last element.
StackRigidOperationCodes StackBack (__overload(StackRigid) *stack, StackElementType *value)
Free stack memory.
StackRigidOperationCodes StackClear (__overload(StackRigid) *stack)
Clear the stack.
StackRigidOperationCodes StackDestruct (__overload(StackRigid) **stack)
Free stack memory.
void StackDump (__overload(StackRigid) *stack, const int line, const char *file, const char *why)
Dumps debug information about the stack.
StackRigidOperationCodes StackPop (__overload(StackRigid) **stack, StackElementType *value)
Pop value from the end of the stack The operation can perform reallocations if there is too much space.
StackRigidOperationCodes StackPush (__overload(StackRigid) **stack, StackElementType value)
Push the value to the stack The operation can perform reallocations if there is not enough space.
size_t StackRigidMemoryUse (__overload(StackRigid) *stack)
Memory alocated for the Stack.
StackRigidState StackValidate (__overload(StackRigid) *stack)
Perform all stack checks: checksums, general constrains.
Variables
FILE * logFile
Macro Definition Documentation
__overload
#define __overload(FUNC) EVALUATOR(FUNC, StackElementType)
EVALUATOR
#define EVALUATOR(x, y) PASTER(x,y)
IGNORE_VALIDITY
#define IGNORE_VALIDITY
PASTER
#define PASTER(x, y) x ## _ ## y
Default element dump instruction.
By default, it will be stack of ints
StackElementDump
#define StackElementDump(FILE, VALUE) {fprintf(FILE, `%g`, VALUE);}
StackElementType
#define StackElementType double
Typedef Documentation
StackRigidOperationCodes
typedef enum StackRigidOperationCodes StackRigidOperationCodes
Codes returned after operations on Stack.
StackRigidState
typedef enum StackRigidState StackRigidState
Codes characterizing Stack state.
Enumeration Type Documentation
StackRigidOperationCodes
enum StackRigidOperationCodes
Codes returned after operations on Stack.
Enumerator
STACK_OP_OK Succesful operation.
STACK_OP_UNDERFLOW Tried to get value from the empty stack.
STACK_OP_OVERFLOW Stack overflow and new memory allocation failed.
STACK_OP_NOMEMORY No memory for stack alocations.
STACK_OP_INTEGRITYERR Stack memory was altered by some outer access.
STACK_OP_NULL Found NULL pointer during the operation.
STACK_OP_PTRINVALID Found invalid pointer during the operation.
                                     {
    STACK_OP_OK,
    STACK_OP_UNDERFLOW,
    STACK_OP_OVERFLOW,
    STACK_OP_NOMEMORY,
    STACK_OP_INTEGRITYERR,
    STACK_OP_NULL,
    STACK_OP_PTRINVALID
} StackRigidOperationCodes;
StackRigidState
enum StackRigidState
Codes characterizing Stack state.
Enumerator
STACK_ST_OK Stack is running as expected.
STACK_ST_INTEGRITYERR Stack was altered by some outer access.
STACK_ST_UNINITIALIZED Stack is uninitialized.
STACK_ST_NULL Found NULL pointer during the operation.
                            {
    STACK_ST_OK,
    STACK_ST_INTEGRITYERR,
    STACK_ST_UNINITIALIZED,
    STACK_ST_NULL
} StackRigidState;
Function Documentation
__overload()
struct __overload (StackRigid) const
The main StackRigid struct.
Create new stack with pre-defined capacity.
Parameters
 in capacity initial stack capacity. Set to 0 if you want the stack to adopt automaticaly.
 in,out logFile file for logging
Returns
new stack pointer or NULL if impossible
                              {
    unsigned long checkSum;
    unsigned long checkSumVital;
    size_t capacity;
    size_t size;
    FILE* logFile;
    StackElementType data[1];
};
__StackGetChecksum()
static unsigned long __StackGetChecksum (__overload(StackRigid) * stack) [static]
Claculates big Stack checksum. Uses Adler-32 method.
Attention
Not for the manual use!
* Stack memory : [ checkSum checkSumVital capacity size logFile | value 1, value 2, ..., value n || ___garbage area___]
* Release:
* ________________from here ^__________________________________________________________^to here
* Debug:
* ________________from here ^______________________________________________________________________________^to here
* 
Parameters
 in stack Stack that checksums are needed to be updated
__StackGetChecksumVital()
static unsigned long __StackGetChecksumVital (__overload(StackRigid) * stack) [static]
Uses Adler-32 method. Calculates Stack checksum only for the vital parameters. This is necessary because __StackGetChecksum() relies on capacity and size. If they were changed, behaviour is undefined.
Attention
Not for the manual use!
* Stack memory : [ checkSum checkSumVital capacity size logFile | value 1, value 2, ..., value n || ___garbage area___]
* ______________________________from here ^__________________^to here
* 
Parameters
 in stack Stack that checksums are needed to be updated
__StackReallocate()
static StackRigidOperationCodes __StackReallocate (__overload(StackRigid) ** stack, short int direction) [static]
Reallocates Stack if needed.
Attention
Not for the manual use!
Parameters
 in,out stack Stack to be reallocated
 in direction which direction reallocations are available. > 0 -> expand space if needed, < 0 -> shrink space if needed
__StackUpdateChecksum()
static void __StackUpdateChecksum (__overload(StackRigid) * stack) [static]
Updates Stack checksums. Does not take into account bytes inside the stack but outside of its last element.
Attention
Not for the manual use!
* Stack memory :  [ __stack area__ | value 1, value 2, ..., value n || ___garbage area___]
* ____________________________________________________________________^ alterations in this area are not checked
* 
Parameters
 in,out stack Stack that checksums are needed to be updated
StackBack()
StackRigidOperationCodes StackBack (__overload(StackRigid) * stack, StackElementType * value)
Free stack memory.
Parameters
 out stack Stack to be used
Returns
the outcome of the operation
                                                                                           {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_NULL;
    
    
    StackRigidState integrityChecks = StackValidate(stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(stack, "StackBack operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    if(stack->size == 0)
        return STACK_OP_UNDERFLOW;
    
    *value = stack->data[stack->size - 1];
    return STACK_OP_OK;
}
References istack_pointer_valid(), STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by OPEXE_FUNC().
StackClear()
StackRigidOperationCodes StackClear (__overload(StackRigid) * stack)
Clear the stack.
Parameters
 in,out stack Stack to be changed
Returns
the outcome of the operation
                                                                   {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_NULL;
    
    
    StackRigidState integrityChecks = StackValidate(stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(stack, "StackClear operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    stack->size = 0;
    
    return STACK_OP_OK;
}
References istack_pointer_valid(), STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by OPEXE_FUNC().
StackDestruct()
StackRigidOperationCodes StackDestruct (__overload(StackRigid) ** stack)
Free stack memory.
Parameters
 in,out stack Stack to be distructed
Returns
the outcome of the operation
                                                                        {
    if (!istack_pointer_valid(stack, sizeof(stack))) {
        return STACK_OP_NULL;
    }
    if (!istack_pointer_valid(*stack, sizeof(*stack))) {
        return STACK_OP_NULL;
    }
    StackRigidState checks = StackValidate(*stack);
    if (checks == STACK_ST_OK){
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        for(char* cursor = (char*)(*stack); cursor < (char*)(*stack) + memoryNow; cursor++)
            *cursor = 0;
    }
    free(*stack);
    return STACK_OP_OK;
}
References istack_pointer_valid(), STACK_OP_NULL, STACK_OP_OK, STACK_ST_OK, StackRigidMemoryUse(), and StackValidate().
StackDump()
void StackDump (__overload(StackRigid) * stack, const int line, const char * file, const char * why)
Dumps debug information about the stack.
Parameters
 in stack Stack to be dumped
                                                                                                  {
    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wformat"
    time_t rawtime = time(NULL);
    struct tm *ptm = localtime(&rawtime);
    
    if (!istack_pointer_valid(stack, sizeof(stack))){
        fprintf(stdin, "\nStack dump is impossible: NULL pointer\n");
        return;
    }
    
    FILE* output = stack->logFile;
    if (!istack_pointer_valid(output, sizeof(output))) {
        output = stdout;
        printf("\nWarning! Specified dump output is inavailbale! Selecting stdout.\n");
    }
    
    fprintf(output, "=================================\n");
    fprintf(output, "Stack dump %s", asctime(ptm));
    fprintf(output, "Line: %d\nFile: %s\n", line, file);
    if (why[0] != '\0')
    fprintf(output, "Problem: %s\n", why);
    
    if (istack_pointer_valid(stack, sizeof(stack))) {
        fprintf(output, "Stack (");
        const char *status = "ok";
        StackRigidState checks = StackValidate(stack);
        switch (checks) {
            case STACK_ST_INTEGRITYERR:
                status = "INTEGRITY ERROR SPOTTED";
                break;
            case STACK_ST_UNINITIALIZED:
                status = "UNINITIALIZED";
                break;
            case STACK_ST_OK:
                status = "ok";
                break;
            case STACK_ST_NULL:
                status = "NULL POINTER";
                break;
        }
        fprintf(output, "%s", status);
        fprintf(output, ")");
        fprintf(output, " [%p]: {\n", (void*)stack);
        if (checks != STACK_ST_OK) {
            fprintf(output, "ERROR! Stack structure was corrupted.\nThe data below was changed from the outside.\nThis can fail!\n");
        }
        fprintf(output, "\t size : %lu\n", stack->size);
        fprintf(output, "\t capacity : %lu\n", stack->capacity);
        fprintf(output, "\t checkSum : %lx\n", stack->checkSumVital);
        fprintf(output, "\tcheckSumVital : %lx\n", stack->checkSum);
        
        fprintf(output, "\tdata [%p]: {\n", (void*)stack->data);
        if (checks == STACK_ST_OK) {
        size_t i = 0;
        for (i = 0; i < stack->size; i++) {
            fprintf(output, "\t\t");
            fprintf(output, "*[%lu] : ", i);
            fprintf(output, "[%p] ",(void*)(stack->data + i));
            StackElementDump(stack->logFile, stack->data[i]);
            fprintf(output, "\n");
        }
        fprintf(output, "\t\t _______\n");
        if (stack->size < stack->capacity) {
            fprintf(output, "\t\t [%lu] : GARBAGE(", i);
            fprintf(output, "[%p] ",(void*)(stack->data + i));
            StackElementDump(stack->logFile, stack->data[i]);
            fprintf(output, ")\n");
        }
        if (stack->size + 1< stack->capacity && stack->size + 1 > stack->size) {
            fprintf(output, "\t\t [%lu] : GARBAGE(", i + 1);
            fprintf(output, "[%p] ", (void*)(stack->data + i + 1));
            StackElementDump(stack->logFile, stack->data[i + 1]);
            fprintf(output, ")\n");
        }
        } else{
            fprintf(output, "\t\tDATA CAN'T BE READED\n");
        }
        
        fprintf(output, "\t}\n");
        fprintf(output, "}\n");
        
        const size_t memory = StackRigidMemoryUse(stack);
        fprintf(output, "Size allocated : %lu bytes\n", memory);
        fprintf(output, "Raw Stack size : %lu bytes\n", sizeof(__overload(StackRigid)));
        fprintf(output, " Element size : %lu bytes\n", sizeof(StackElementType));
        fprintf(output, " Block end : %p\n", (void*)((char*)stack + memory));
    }
    fprintf(output, "=================================\n");
    fflush(NULL);
    #pragma clang diagnostic pop
}
References __overload(), i, istack_pointer_valid(), memory, STACK_ST_INTEGRITYERR, STACK_ST_NULL, STACK_ST_OK, STACK_ST_UNINITIALIZED, StackElementDump, StackElementType, StackRigidMemoryUse(), and StackValidate().
Referenced by main().
StackPop()
StackRigidOperationCodes StackPop (__overload(StackRigid) ** stack, StackElementType * value)
Pop value from the end of the stack The operation can perform reallocations if there is too much space.
Parameters
 in,out stack Stack to be distructed
 out value value to be pushed
Returns
the outcome of the operation
                                                                                            {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_NULL;
    
    StackRigidState integrityChecks = StackValidate(*stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(*stack, "StackPop operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    if((*stack)->size == 0)
        return STACK_OP_UNDERFLOW;
    
    *value = (*stack)->data[(*stack)->size - 1];
    (*stack)->size -= 1;
    
    StackRigidOperationCodes realocRes = __StackReallocate(stack, -1);
    if (realocRes == STACK_OP_OK)
        __StackUpdateChecksum(*stack);
    else
        return realocRes;
    
    return STACK_OP_OK;
}
References __StackReallocate(), __StackUpdateChecksum(), istack_pointer_valid(), STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by if(), and OPEXE_FUNC().
StackPush()
StackRigidOperationCodes StackPush (__overload(StackRigid) ** stack, StackElementType value)
Push the value to the stack The operation can perform reallocations if there is not enough space.
Parameters
 in,out stack Stack to be changed
 in value value to be pushed
Returns
the outcome of the operation
                                                                                           {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_PTRINVALID;
    if (!istack_pointer_valid(*stack, sizeof(*stack)))
        return STACK_OP_PTRINVALID;
    
    
    StackRigidState integrityChecks = StackValidate(*stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(*stack, "StackPush operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    
    StackRigidOperationCodes reallocResult = __StackReallocate(stack, 1);
    
    if (reallocResult != STACK_OP_OK) {
        StackDumpWrapperWhy(*stack, "StackPop operation spotted integrity error during the reallocation");
        return reallocResult;
    }
    
    (*stack)->data[(*stack)->size] = value;
    (*stack)->size += 1;
    
    __StackUpdateChecksum(*stack);
    
    if ((*stack)->size == 0) {
        return STACK_OP_OVERFLOW;
    }
    return STACK_OP_OK;
}
References __StackReallocate(), __StackUpdateChecksum(), istack_pointer_valid(), STACK_OP_INTEGRITYERR, STACK_OP_OK, STACK_OP_OVERFLOW, STACK_OP_PTRINVALID, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by OPEXE_FUNC().
StackRigidMemoryUse()
size_t StackRigidMemoryUse (__overload(StackRigid) * stack)
Memory alocated for the Stack.
Parameters
 in stack Stack to be checked
Returns
alocated bytes
                                                           {
    assert(stack);
    return sizeof(__overload(StackRigid)) + (stack->capacity - 1) * sizeof(StackElementType);
}
References __overload(), and StackElementType.
Referenced by __StackGetChecksum(), __StackReallocate(), StackDestruct(), and StackDump().
StackValidate()
StackRigidState StackValidate (__overload(StackRigid) * stack)
Perform all stack checks: checksums, general constrains.
Parameters
 in stack Stack to be validated
Returns
calculated state
                                                              {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_ST_NULL;
    
    #ifdef IGNORE_VALIDITY
        return STACK_ST_OK;
    #endif
    
    #ifndef IGNORE_VALIDITY
        if (stack->size > stack->capacity || stack->checkSum == 0 || stack->checkSumVital == 0)
            return STACK_ST_INTEGRITYERR;
    #endif
    #ifndef IGNORE_VALIDITY
        unsigned long currentChecksumVital = __StackGetChecksumVital(stack);
        if (currentChecksumVital != stack->checkSumVital || currentChecksumVital == 0)
            return STACK_ST_INTEGRITYERR;
        
        unsigned long currentChecksum = __StackGetChecksum(stack);
        if (currentChecksum != stack->checkSum || currentChecksum == 0)
            return STACK_ST_INTEGRITYERR;
    #endif
    return STACK_ST_OK;
}
References __StackGetChecksum(), __StackGetChecksumVital(), istack_pointer_valid(), STACK_ST_INTEGRITYERR, STACK_ST_NULL, and STACK_ST_OK.
Referenced by StackBack(), StackClear(), StackDestruct(), StackDump(), StackPop(), and StackPush().
Variable Documentation
logFile
FILE* logFile