SoftProcessorUnit/Assembly/Helpers/AnalysisAndPreparing/StringDistance.hpp File Reference
#include <stdio.h>
Data Structures
struct LevenshteinEdit
Typedefs
typedef struct LevenshteinEdit LevenshteinEdit
Enumerations
enum LevenshteinEditType { INSERTION,
DELETION,
SUBSTITUTION,
NONE
 }
Functions
unsigned int levenshtein_distance (const char *str1, const char *str2, LevenshteinEdit **script)
static unsigned int levenshtein_matrix_calculate (LevenshteinEdit **mat, const char *str1, size_t len1, const char *str2, size_t len2)
static LevenshteinEdit ** levenshtein_matrix_create (size_t len1, size_t len2)
static int min3 (int a, int b, int c)
size_t trimwhitespace (char *out, size_t len, const char *str)
Data Structure Documentation
struct LevenshteinEdit
Data Fields
char
arg1
char
arg2
unsigned int
pos
struct LevenshteinEdit *
prev
unsigned int
score
LevenshteinEditType
type
Typedef Documentation
LevenshteinEdit
typedef struct LevenshteinEdit LevenshteinEdit
Enumeration Type Documentation
LevenshteinEditType
enum LevenshteinEditType
Enumerator
INSERTION
DELETION
SUBSTITUTION
NONE
             {
    INSERTION,
    DELETION,
    SUBSTITUTION,
    NONE
} LevenshteinEditType;
Function Documentation
levenshtein_distance()
unsigned int levenshtein_distance (const char * str1, const char * str2, LevenshteinEdit ** script)
{
    const size_t len1 = strlen(str1), len2 = strlen(str2);
    unsigned int i, distance;
    LevenshteinEdit **mat, *head;
    
    /* If either string is empty, the distance is the other string's length */
    if (len1 == 0) {
        return (unsigned int)len2;
    }
    if (len2 == 0) {
        return (unsigned int)len1;
    }
    /* Initialise the matrix */
    mat = levenshtein_matrix_create(len1, len2);
    if (!mat) {
        *script = NULL;
        return 0;
    }
    /* Main algorithm */
    distance = levenshtein_matrix_calculate(mat, str1, len1, str2, len2);
    /* Read back the edit script */
    *script = (LevenshteinEdit *)malloc(distance * sizeof(LevenshteinEdit));
    if (*script) {
        i = distance - 1;
        for (head = &mat[len1][len2];
             head->prev != NULL;
             head = head->prev) {
            if (head->type != NONE) {
                memcpy(*script + i, head, sizeof(LevenshteinEdit));
                i--;
            }
        }
    }
    else {
        distance = 0;
    }
    /* Clean up */
    for (i = 0; i <= len1; i++) {
        free(mat[i]);
    }
    free(mat);
    
    return distance;
}
References levenshtein_matrix_calculate(), levenshtein_matrix_create(), NONE, LevenshteinEdit::prev, and LevenshteinEdit::type.
Referenced by bestMatchCommand().
levenshtein_matrix_calculate()
static unsigned int levenshtein_matrix_calculate (LevenshteinEdit ** mat, const char * str1, size_t len1, const char * str2, size_t len2) [static]
levenshtein_matrix_create()
static LevenshteinEdit** levenshtein_matrix_create (size_t len1, size_t len2) [static]
min3()
static int min3 (int a, int b, int c) [static]
trimwhitespace()
size_t trimwhitespace (char * out, size_t len, const char * str)
{
  if(len == 0)
    return 0;
  const char *end;
  size_t out_size;
  // Trim leading space
  while(isspace((unsigned char)*str)) str++;
  if(*str == 0) // All spaces?
  {
    *out = 0;
    return 1;
  }
  // Trim trailing space
  end = str + strlen(str) - 1;
  while(end > str && isspace((unsigned char)*end)) end--;
  end++;
  // Set output size to minimum of trimmed string length and buffer size minus 1
  out_size = (end - str) < (long)len - 1 ? (size_t)(end - str) : len - 1;
  // Copy trimmed string and add null terminator
  memcpy(out, str, out_size);
  out[out_size] = 0;
  return out_size;
}
References isspace().
Referenced by analyzeInstructionErrors().