JMPLabelsStore Struct Reference
#include `LabelsStore.hpp`
Public Member Functions
JMPLabelsStore ()
~JMPLabelsStore ()
JMPLabel * getLabel (char *label) const
JMPLabel * getLabelByToPosition (long int pos) const
long int getLabelToPosition (char *label) const
void newLabel (char *label)
void setLabelFromPosition (char *label, unsigned int position)
void setLabelToPosition (char *label, unsigned int position)
Data Fields
JMPLabel * first
JMPLabel * last
Constructor & Destructor Documentation
JMPLabelsStore()
JMPLabelsStore::JMPLabelsStore ()
                               {
    this->first = nullptr;
    this->last = nullptr;
}
References first, and last.
 JMPLabelsStore()
JMPLabelsStore::~JMPLabelsStore ()
                                {
    JMPLabel* current = this->first;
    
    while (current != nullptr) {
        JMPLabel* next = current->next;
        delete current;
        current = next;
    }
}
References first, and JMPLabel::next.
Member Function Documentation
getLabel()
JMPLabel * JMPLabelsStore::getLabel (char * label) const
                                                    {
    JMPLabel* current = this->first;
    while (current != nullptr) {
        if (strcmp(current->name, label) == 0) {
            return current;
        }
        current = current->next;
    }
    
    return nullptr;
}
References first, JMPLabel::name, and JMPLabel::next.
Referenced by setLabelFromPosition(), and setLabelToPosition().
getLabelByToPosition()
JMPLabel * JMPLabelsStore::getLabelByToPosition (long int pos) const
                                                                 {
    JMPLabel* current = this->first;
    while (current != nullptr) {
        if (current->positionTo == pos) {
            return current;
        }
        current = current->next;
    }
    return nullptr;
}
References first, JMPLabel::next, and JMPLabel::positionTo.
getLabelToPosition()
long int JMPLabelsStore::getLabelToPosition (char * label) const
                                                             {
    JMPLabel* current = this->first;
    while (current != nullptr) {
        if (strcmp(current->name, label) == 0) {
            return current->positionTo;
        }
        current = current->next;
    }
    return -1;
}
References first, JMPLabel::name, JMPLabel::next, and JMPLabel::positionTo.
newLabel()
void JMPLabelsStore::newLabel (char * label)
                                         {
    JMPLabel* previous = this->last;
    JMPLabel* newLabel = new JMPLabel(this->last, label);
    if (this->last == nullptr)
        this->first = (this->last = newLabel);
    else
        this->last = newLabel;
    
    
    JMPLabel* current = this->first;
    while (current != nullptr && current != this->last) {
        if (strcmp(current->name, newLabel->name) == 0){
            previous->next = nullptr;
            this->last = previous;
            delete newLabel;
            throw "Label exists";
        }
        
        current = current->next;
    }
}
References first, last, JMPLabel::name, and JMPLabel::next.
Referenced by parseLabel(), setLabelFromPosition(), and setLabelToPosition().
setLabelFromPosition()
void JMPLabelsStore::setLabelFromPosition (char * label, unsigned int position)
                                                                            {
    JMPLabel* current = this->getLabel(label);
    
    if (current == nullptr) {
        this->newLabel(label);
        current = this->last;
    }
    current->positionFrom = (long)position;
}
References getLabel(), last, newLabel(), and JMPLabel::positionFrom.
setLabelToPosition()
void JMPLabelsStore::setLabelToPosition (char * label, unsigned int position)
                                                                          {
    JMPLabel* current = this->getLabel(label);
    
    if (current == nullptr) {
        this->newLabel(label);
        current = this->last;
    }
    
    current->wasUsed();
    if (current->used != 1) {
        throw "This label was used";
    }
    current->positionTo = (long)position;
}
References getLabel(), last, newLabel(), JMPLabel::positionTo, JMPLabel::used, and JMPLabel::wasUsed().
Referenced by setLabelPos().
Field Documentation
first
JMPLabel* JMPLabelsStore::first
Referenced by JMPLabelsStore(), ~JMPLabelsStore(), analyzeLabelsErrors(), evaluateLabels(), getLabel(), getLabelByToPosition(), getLabelToPosition(), labelsTableComplete(), and newLabel().
last
JMPLabel* JMPLabelsStore::last
Referenced by JMPLabelsStore(), newLabel(), setLabelFromPosition(), and setLabelToPosition().
The documentation for this struct was generated from the following files:
SoftProcessorUnit/Assembly/Helpers/LabelHandlers/LabelsStore.hpp
SoftProcessorUnit/Assembly/Helpers/LabelHandlers/LabelsStore.cpp